<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DepartamentoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('departamentos')->insert([
            ['ndepartamento' => 'CAPITAL', 'provincia_id' => 9], 
            ['ndepartamento' => 'CHILECITO', 'provincia_id' => 9], 
            ['ndepartamento' => 'CHAMICAL', 'provincia_id' => 9], 
            ['ndepartamento' => 'ARAUCO', 'provincia_id' => 9], 
            ['ndepartamento' => 'CASTRO BARROS', 'provincia_id' => 9], 
            ['ndepartamento' => 'CORONEL FELIPE VARELA', 'provincia_id' => 9], 
            ['ndepartamento' => 'FAMATINA', 'provincia_id' => 9], 
            ['ndepartamento' => 'GENERAL ANGEL V. PEÑALOZA', 'provincia_id' => 9],
            ['ndepartamento' => 'GENERAL BELGRANO', 'provincia_id' => 9],
            ['ndepartamento' => 'GENERAL JUAN F. QUIROGA', 'provincia_id' => 9],
            ['ndepartamento' => 'GENERAL LAMADRID', 'provincia_id' => 9],
            ['ndepartamento' => 'GENERAL OCAMPO', 'provincia_id' => 9],
            ['ndepartamento' => 'GENERAL SAN MARTIN', 'provincia_id' => 9],
            ['ndepartamento' => 'INDEPENDENCIA', 'provincia_id' => 9],
            ['ndepartamento' => 'ROSARIO VERA PEÑALOZA', 'provincia_id' => 9],
            ['ndepartamento' => 'SAN BLAS DE LOS SAUCES', 'provincia_id' => 9],
            ['ndepartamento' => 'SANAGASTA', 'provincia_id' => 9],
            ['ndepartamento' => 'VINCHINA', 'provincia_id' => 9],
            ['ndepartamento' => 'ALMAGRO', 'provincia_id' => 3],
            ['ndepartamento' => 'BALVANERA', 'provincia_id' => 3],
            ['ndepartamento' => 'BARRACAS', 'provincia_id' => 3],
            ['ndepartamento' => 'BELGRANO', 'provincia_id' => 3],
            ['ndepartamento' => 'BOCA', 'provincia_id' => 3],
            ['ndepartamento' => 'BOEDO', 'provincia_id' => 3],
            ['ndepartamento' => 'CABALLITO', 'provincia_id' => 3],
            ['ndepartamento' => 'CHACARITA', 'provincia_id' => 3],
            ['ndepartamento' => 'COGHLAN', 'provincia_id' => 3],
            ['ndepartamento' => 'COLEGIALES', 'provincia_id' => 3],
            ['ndepartamento' => 'CONSTITUCIËN', 'provincia_id' => 3],
            ['ndepartamento' => 'FLORES', 'provincia_id' => 3],
            ['ndepartamento' => 'FLORESTA', 'provincia_id' => 3],
            ['ndepartamento' => 'LINIERS', 'provincia_id' => 3],
            ['ndepartamento' => 'MATADEROS', 'provincia_id' => 3],
            ['ndepartamento' => 'MONTE CASTRO', 'provincia_id' => 3],
            ['ndepartamento' => 'MONTSERRAT', 'provincia_id' => 3],
            ['ndepartamento' => 'NUEVA POMPEYA', 'provincia_id' => 3],
            ['ndepartamento' => 'NUÑEZ', 'provincia_id' => 3],
            ['ndepartamento' => 'PALERMO', 'provincia_id' => 3],
            ['ndepartamento' => 'PARQUE AVELLANEDA', 'provincia_id' => 3],
            ['ndepartamento' => 'PARQUE CHACABUCO', 'provincia_id' => 3],
            ['ndepartamento' => 'PARQUE PATRICIOS', 'provincia_id' => 3],
            ['ndepartamento' => 'PATERNAL', 'provincia_id' => 3],
            ['ndepartamento' => 'RECOLETA', 'provincia_id' => 3],
            ['ndepartamento' => 'RETIRO', 'provincia_id' => 3],
            ['ndepartamento' => 'SAAVEDRA', 'provincia_id' => 3],
            ['ndepartamento' => 'SAN CRISTËBAL', 'provincia_id' => 3],
            ['ndepartamento' => 'SAN NICOLAS', 'provincia_id' => 3],
            ['ndepartamento' => 'SAN TELMO', 'provincia_id' => 3],
            ['ndepartamento' => 'VELEZ SARSFIELD', 'provincia_id' => 3],
            ['ndepartamento' => 'VERSALLES', 'provincia_id' => 3],
            ['ndepartamento' => 'VILLA CRESPO', 'provincia_id' => 3],
            ['ndepartamento' => 'VILLA DEL PARQUE', 'provincia_id' => 3],
            ['ndepartamento' => 'VILLA DEVOTO', 'provincia_id' => 3],
            ['ndepartamento' => 'VILLA GENERAL MITRE', 'provincia_id' => 3],
            ['ndepartamento' => 'VILLA LUGANO', 'provincia_id' => 3],
            ['ndepartamento' => 'VILLA LURO', 'provincia_id' => 3],
            ['ndepartamento' => 'VILLA ORT?ZAR', 'provincia_id' => 3],
            ['ndepartamento' => 'VILLA PUEYRREDËN', 'provincia_id' => 3],
            ['ndepartamento' => 'VILLA REAL', 'provincia_id' => 3],
            ['ndepartamento' => 'VILLA RIACHUELO', 'provincia_id' => 3],
            ['ndepartamento' => 'VILLA SANTA RITA', 'provincia_id' => 3],
            ['ndepartamento' => 'VILLA SOLDATI', 'provincia_id' => 3],
            ['ndepartamento' => 'VILLA URQUIZA', 'provincia_id' => 3],
            ['ndepartamento' => 'ZONA PORTUARIA', 'provincia_id' => 3],
            ['ndepartamento' => 'ATREUCO', 'provincia_id' => 1],
            ['ndepartamento' => 'CALEU CALEU', 'provincia_id' => 1],
            ['ndepartamento' => 'CAPITAL', 'provincia_id' => 1],
            ['ndepartamento' => 'CATRILË', 'provincia_id' => 1],
            ['ndepartamento' => 'CONHELO', 'provincia_id' => 1],
            ['ndepartamento' => 'CURACË', 'provincia_id' => 1],
            ['ndepartamento' => 'CHALILEO', 'provincia_id' => 1],
            ['ndepartamento' => 'CHAPALEUF?', 'provincia_id' => 1],
            ['ndepartamento' => 'CHICAL CË', 'provincia_id' => 1],
            ['ndepartamento' => 'GUATRACH?', 'provincia_id' => 1],
            ['ndepartamento' => 'HUCAL', 'provincia_id' => 1],
            ['ndepartamento' => 'UHUEL CALEL', 'provincia_id' => 1],
            ['ndepartamento' => 'LIMAY MAHUIDA', 'provincia_id' => 1],
            ['ndepartamento' => 'LOVENTU?', 'provincia_id' => 1],
            ['ndepartamento' => 'MARACË', 'provincia_id' => 1],
            ['ndepartamento' => 'PUEL?N', 'provincia_id' => 1],
            ['ndepartamento' => 'QUEM? QUEM?', 'provincia_id' => 1],
            ['ndepartamento' => 'RANCUL', 'provincia_id' => 1],
            ['ndepartamento' => 'REALICË', 'provincia_id' => 1],
            ['ndepartamento' => 'TOAY', 'provincia_id' => 1],
            ['ndepartamento' => 'TRENEL', 'provincia_id' => 1],
            ['ndepartamento' => 'UTRAC?N', 'provincia_id' => 1],
            ['ndepartamento' => 'ALUMIN?', 'provincia_id' => 2],
            ['ndepartamento' => 'AÐELO', 'provincia_id' => 2],
            ['ndepartamento' => 'CATAN LIL', 'provincia_id' => 2],
            ['ndepartamento' => 'COLLËN CUR?', 'provincia_id' => 2],
            ['ndepartamento' => 'CONFLUENCIA', 'provincia_id' => 2],
            ['ndepartamento' => 'CHOS MALAL', 'provincia_id' => 2],
            ['ndepartamento' => 'HUILICHES', 'provincia_id' => 2],
            ['ndepartamento' => 'LACAR', 'provincia_id' => 2],
            ['ndepartamento' => 'LONCOPU?', 'provincia_id' => 2],
            ['ndepartamento' => 'LOS LAGOS', 'provincia_id' => 2],
            ['ndepartamento' => 'MINAS', 'provincia_id' => 2],
            ['ndepartamento' => 'ÐORQU?N', 'provincia_id' => 2],
            ['ndepartamento' => 'PEHUENCHES', 'provincia_id' => 2],
            ['ndepartamento' => 'PIC?N LEUF?', 'provincia_id' => 2],
            ['ndepartamento' => 'PICUNCHES', 'provincia_id' => 2],
            ['ndepartamento' => 'ZAPALA', 'provincia_id' => 2],
            ['ndepartamento' => 'ADOLFO ALSINA', 'provincia_id' => 3],
            ['ndepartamento' => 'ADOLFO GONZALES CHAVES', 'provincia_id' => 3],
            ['ndepartamento' => 'ALBERTI', 'provincia_id' => 3],
            ['ndepartamento' => 'ALMIRANTE BROWN', 'provincia_id' => 3],
            ['ndepartamento' => 'AVELLANEDA', 'provincia_id' => 3],
            ['ndepartamento' => 'AYACUCHO', 'provincia_id' => 3],
            ['ndepartamento' => 'AZUL', 'provincia_id' => 3],
            ['ndepartamento' => 'BAH?A BLANCA', 'provincia_id' => 3],
            ['ndepartamento' => 'BALCARCE', 'provincia_id' => 3],
            ['ndepartamento' => 'BARADERO', 'provincia_id' => 3],
            ['ndepartamento' => 'BARTOLOM? MITRE', 'provincia_id' => 3],
            ['ndepartamento' => 'BENITO JUáREZ', 'provincia_id' => 3],
            ['ndepartamento' => 'BERAZATEGUI', 'provincia_id' => 3],
            ['ndepartamento' => 'BERISSO', 'provincia_id' => 3],
            ['ndepartamento' => 'BOLIVAR', 'provincia_id' => 3],
            ['ndepartamento' => 'BRAGADO', 'provincia_id' => 3],
            ['ndepartamento' => 'BRANDSEN', 'provincia_id' => 3],
            ['ndepartamento' => 'CAMPANA', 'provincia_id' => 3],
            ['ndepartamento' => 'CAÐUELAS', 'provincia_id' => 3],
            ['ndepartamento' => 'CAPIT?N SARMIENTO', 'provincia_id' => 3],
            ['ndepartamento' => 'CARLOS CASARES', 'provincia_id' => 3],
            ['ndepartamento' => 'CARLOS TEJEDOR', 'provincia_id' => 3],
            ['ndepartamento' => 'CARMEN DE ARECO', 'provincia_id' => 3],
            ['ndepartamento' => 'CASTELLI', 'provincia_id' => 3],
            ['ndepartamento' => 'COLËN', 'provincia_id' => 3],
            ['ndepartamento' => 'CORONEL DE MARINA L. ROSALE', 'provincia_id' => 3],
            ['ndepartamento' => 'CORONEL DORREGO', 'provincia_id' => 3],
            ['ndepartamento' => 'CORONEL PRINGLES', 'provincia_id' => 3],
            ['ndepartamento' => 'CORONEL SU?REZ', 'provincia_id' => 3],
            ['ndepartamento' => 'CHACABUCO', 'provincia_id' => 3],
            ['ndepartamento' => 'CHASCOM?S', 'provincia_id' => 3],
            ['ndepartamento' => 'CHIVILCOY', 'provincia_id' => 3],
            ['ndepartamento' => 'DAIREAUX', 'provincia_id' => 3],
            ['ndepartamento' => 'DOLORES', 'provincia_id' => 3],
            ['ndepartamento' => 'ENSENADA', 'provincia_id' => 3],
            ['ndepartamento' => 'ESCOBAR', 'provincia_id' => 3],
            ['ndepartamento' => 'ESTEBAN ECHEVERR?A', 'provincia_id' => 3],
            ['ndepartamento' => 'EXALTACIËN DE LA CRUZ', 'provincia_id' => 3],
            ['ndepartamento' => 'FLORENCIO VARELA', 'provincia_id' => 3],
            ['ndepartamento' => 'FLORENTINO AMEGHINO', 'provincia_id' => 3],
            ['ndepartamento' => 'GENERAL ALVARADO', 'provincia_id' => 3],
            ['ndepartamento' => 'GENERAL ALVEAR', 'provincia_id' => 3],
            ['ndepartamento' => 'GENERAL ARENALES', 'provincia_id' => 3],
            ['ndepartamento' => 'GENERAL BELGRANO', 'provincia_id' => 3],
            ['ndepartamento' => 'GENERAL GUIDO', 'provincia_id' => 3],
            ['ndepartamento' => 'GENERAL JUAN MADARIAGA', 'provincia_id' => 3],
            ['ndepartamento' => 'GENERAL LA MADRID', 'provincia_id' => 3],
            ['ndepartamento' => 'GENERAL LAS HERAS', 'provincia_id' => 3],
            ['ndepartamento' => 'GENERAL LAVALLE', 'provincia_id' => 3],
            ['ndepartamento' => 'GENERAL PAZ', 'provincia_id' => 3],
            ['ndepartamento' => 'GENERAL PINTO', 'provincia_id' => 3],
            ['ndepartamento' => 'GENERAL PUEYRREDËN', 'provincia_id' => 3],
            ['ndepartamento' => 'GENERAL RODRIGUEZ', 'provincia_id' => 3],
            ['ndepartamento' => 'GENERAL SAN MART?N', 'provincia_id' => 3],
            ['ndepartamento' => 'GENERAL SARMIENTO', 'provincia_id' => 3],
            ['ndepartamento' => 'GENERAL VIAMONTE', 'provincia_id' => 3],
            ['ndepartamento' => 'GENERAL VILLEGAS', 'provincia_id' => 3],
            ['ndepartamento' => 'GUAMIN?', 'provincia_id' => 3],
            ['ndepartamento' => 'HIPËLITO YRIGOYEN', 'provincia_id' => 3],
            ['ndepartamento' => 'JUN?N', 'provincia_id' => 3],
            ['ndepartamento' => 'LA COSTA', 'provincia_id' => 3],
            ['ndepartamento' => 'LA MATANZA','provincia_id' => 3],
            ['ndepartamento' => 'LA PLATA','provincia_id' => 3],
            ['ndepartamento' => 'LAN?S','provincia_id' => 3],
            ['ndepartamento' => 'LAPRIDA','provincia_id' => 3],
            ['ndepartamento' => 'LAS FLORES','provincia_id' => 3],
            ['ndepartamento' => 'LEANDRO N. ALEM','provincia_id' => 3],
            ['ndepartamento' => 'LINCOLN','provincia_id' => 3],
            ['ndepartamento' => 'LOBER?A','provincia_id' => 3],
            ['ndepartamento' => 'LOBOS','provincia_id' => 3],
            ['ndepartamento' => 'LOMAS DE ZAMORA','provincia_id' => 3],
            ['ndepartamento' => 'LUJ?N','provincia_id' => 3],
            ['ndepartamento' => 'MAGDALENA','provincia_id' => 3],
            ['ndepartamento' => 'MAIP?','provincia_id' => 3],
            ['ndepartamento' => 'MAR CHIQUITA','provincia_id' => 3],
            ['ndepartamento' => 'MARCOS PAZ','provincia_id' => 3],
            ['ndepartamento' => 'MERCEDES','provincia_id' => 3],
            ['ndepartamento' => 'MERLO','provincia_id' => 3],
            ['ndepartamento' => 'MONTE','provincia_id' => 3],
            ['ndepartamento' => 'MONTE HERMOSO','provincia_id' => 3],
            ['ndepartamento' => 'MORENO','provincia_id' => 3],
            ['ndepartamento' => 'MORËN','provincia_id' => 3],
            ['ndepartamento' => 'NAVARRO','provincia_id' => 3],
            ['ndepartamento' => 'NECOCHEA','provincia_id' => 3],
            ['ndepartamento' => '9 DE JULIO','provincia_id' => 3],
            ['ndepartamento' => 'OLAVARR?A','provincia_id' => 3],
            ['ndepartamento' => 'PATAGONES','provincia_id' => 3],
            ['ndepartamento' => 'PEHUAJË','provincia_id' => 3],
            ['ndepartamento' => 'PELLEGRINI','provincia_id' => 3],
            ['ndepartamento' => 'PERGAMINO','provincia_id' => 3],
            ['ndepartamento' => 'PILA','provincia_id' => 3],
            ['ndepartamento' => 'PILAR','provincia_id' => 3],
            ['ndepartamento' => 'PINAMAR','provincia_id' => 3],
            ['ndepartamento' => 'PU?N','provincia_id' => 3],
            ['ndepartamento' => 'QUILMES','provincia_id' => 3],
            ['ndepartamento' => 'RAMALLO','provincia_id' => 3],
            ['ndepartamento' => 'RAUCH','provincia_id' => 3],
            ['ndepartamento' => 'RIVADAVIA','provincia_id' => 3],
            ['ndepartamento' => 'ROJAS','provincia_id' => 3],
            ['ndepartamento' => 'ROQUE P?REZ', 'provincia_id' => 3],
            ['ndepartamento' => 'SAAVEDRA', 'provincia_id' => 3],
            ['ndepartamento' => 'SALADILLO', 'provincia_id' => 3],
            ['ndepartamento' => 'SALTO', 'provincia_id' => 3],
            ['ndepartamento' => 'SALLIQUELË', 'provincia_id' => 3],
            ['ndepartamento' => 'SAN ANDR?S DE GILES', 'provincia_id' => 3],
            ['ndepartamento' => 'SAN ANTONIO DE ARECO', 'provincia_id' => 3],
            ['ndepartamento' => 'SAN CAYETANO', 'provincia_id' => 3],
            ['ndepartamento' => 'SAN FERNANDO', 'provincia_id' => 3],
            ['ndepartamento' => 'SAN ISIDRO', 'provincia_id' => 3],
            ['ndepartamento' => 'SAN NICOL?S', 'provincia_id' => 3],
            ['ndepartamento' => 'SAN PEDRO', 'provincia_id' => 3],
            ['ndepartamento' => 'SAN VICENTE', 'provincia_id' => 3],
            ['ndepartamento' => 'SUIPACHA', 'provincia_id' => 3],
            ['ndepartamento' => 'TANDIL', 'provincia_id' => 3],
            ['ndepartamento' => 'TAPALQU?', 'provincia_id' => 3],
            ['ndepartamento' => 'TIGRE', 'provincia_id' => 3],
            ['ndepartamento' => 'TORDILLO', 'provincia_id' => 3],
            ['ndepartamento' => 'TORNQUIST', 'provincia_id' => 3],
            ['ndepartamento' => 'TRENQUE LAUQUEN', 'provincia_id' => 3],
            ['ndepartamento' => 'TRES ARROYOS', 'provincia_id' => 3],
            ['ndepartamento' => 'TRES DE FEBRERO', 'provincia_id' => 3],
            ['ndepartamento' => 'TRES LOMAS', 'provincia_id' => 3],
            ['ndepartamento' => '25 DE MAYO', 'provincia_id' => 3],
            ['ndepartamento' => 'VICENTE LËPEZ', 'provincia_id' => 3],
            ['ndepartamento' => 'VILLA GESELL', 'provincia_id' => 3],
            ['ndepartamento' => 'VILLARINO', 'provincia_id' => 3],
            ['ndepartamento' => 'Z?RATE', 'provincia_id' => 3],
            ['ndepartamento' => 'AMBATO', 'provincia_id' => 4],
            ['ndepartamento' => 'ANCASTI', 'provincia_id' => 4],
            ['ndepartamento' => 'ANDALGALA', 'provincia_id' => 4],
            ['ndepartamento' => 'ANTOFAGASTA DE LA SIERRA', 'provincia_id' => 4],
            ['ndepartamento' => 'BELEN', 'provincia_id' => 4],
            ['ndepartamento' => 'CAPAYAN', 'provincia_id' => 4],
            ['ndepartamento' => 'CAPITAL', 'provincia_id' => 4],
            ['ndepartamento' => 'EL ALTO', 'provincia_id' => 4],
            ['ndepartamento' => 'FRAY MAMERTO ESQUIU', 'provincia_id' => 4],
            ['ndepartamento' => 'LA PAZ', 'provincia_id' => 4],
            ['ndepartamento' => 'PACLIN', 'provincia_id' => 4],
            ['ndepartamento' => 'POMAN', 'provincia_id' => 4],
            ['ndepartamento' => 'SANTA MARIA', 'provincia_id' => 4],
            ['ndepartamento' => 'SANTA ROSA', 'provincia_id' => 4],
            ['ndepartamento' => 'TINOGASTA', 'provincia_id' => 4],
            ['ndepartamento' => 'VALLE VIEJO', 'provincia_id' => 4],
            ['ndepartamento' => 'AYACUCHO', 'provincia_id' => 5],
            ['ndepartamento' => 'BELGRANO', 'provincia_id' => 5],
            ['ndepartamento' => 'CORONEL PRINGLES', 'provincia_id' => 5],
            ['ndepartamento' => 'CHACABUCO', 'provincia_id' => 5],
            ['ndepartamento' => 'GENERAL PEDERNERA', 'provincia_id' => 5],
            ['ndepartamento' => 'GOBERNADOR DUPUY', 'provincia_id' => 5],
            ['ndepartamento' => 'JUN?N', 'provincia_id' => 5],
            ['ndepartamento' => 'LA CAPITAL', 'provincia_id' => 5],
            ['ndepartamento' => 'LIBERTADOR GENERAL SAN MART?N', 'provincia_id' => 5],
            ['ndepartamento' => 'CALAMUCHITA', 'provincia_id' => 6],
            ['ndepartamento' => 'CAPITAL', 'provincia_id' => 6],
            ['ndepartamento' => 'COLËN', 'provincia_id' => 6],
            ['ndepartamento' => 'CRUZ DEL EJE', 'provincia_id' => 6],
            ['ndepartamento' => 'GENERAL ROCA', 'provincia_id' => 6],
            ['ndepartamento' => 'GENERAL SAN MART?N', 'provincia_id' => 6],
            ['ndepartamento' => 'ISCHIL?N', 'provincia_id' => 6],
            ['ndepartamento' => 'JU?REZ CELMAN', 'provincia_id' => 6],
            ['ndepartamento' => 'MARCOS JU?REZ', 'provincia_id' => 6],
            ['ndepartamento' => 'MINAS', 'provincia_id' => 6],
            ['ndepartamento' => 'POCHO', 'provincia_id' => 6],
            ['ndepartamento' => 'PRESIDENTE ROQUE SáENZ PEÐA', 'provincia_id' => 6],
            ['ndepartamento' => 'PUNILLA', 'provincia_id' => 6],
            ['ndepartamento' => 'R?O CUARTO', 'provincia_id' => 6],
            ['ndepartamento' => 'R?O PRIMERO', 'provincia_id' => 6],
            ['ndepartamento' => 'R?O SECO', 'provincia_id' => 6],
            ['ndepartamento' => 'R?O SEGUNDO', 'provincia_id' => 6],
            ['ndepartamento' => 'SAN ALBERTO', 'provincia_id' => 6],
            ['ndepartamento' => 'SAN JAVIER', 'provincia_id' => 6],
            ['ndepartamento' => 'SAN JUSTO', 'provincia_id' => 6],
            ['ndepartamento' => 'SANTA MAR?A', 'provincia_id' => 6],
            ['ndepartamento' => 'SOBREMONTE', 'provincia_id' => 6],
            ['ndepartamento' => 'TERCERO ARRIBA', 'provincia_id' => 6],
            ['ndepartamento' => 'TOTORAL', 'provincia_id' => 6],
            ['ndepartamento' => 'TULUMBA', 'provincia_id' => 6],
            ['ndepartamento' => 'UNIËN', 'provincia_id' => 6],
            ['ndepartamento' => 'ADOLFO ALSINA', 'provincia_id' => 7],
            ['ndepartamento' => 'AVELLANEDA', 'provincia_id' => 7],
            ['ndepartamento' => 'BARILOCHE', 'provincia_id' => 7],
            ['ndepartamento' => 'CONESA', 'provincia_id' => 7],
            ['ndepartamento' => 'EL CUY', 'provincia_id' => 7],
            ['ndepartamento' => 'GENERAL ROCA', 'provincia_id' => 7],
            ['ndepartamento' => '9 DE JULIO', 'provincia_id' => 7],
            ['ndepartamento' => 'ÐORQUINCO', 'provincia_id' => 7],
            ['ndepartamento' => 'PICHI MAHU?DA', 'provincia_id' => 7],
            ['ndepartamento' => 'PILCANIYEU', 'provincia_id' => 7],
            ['ndepartamento' => 'SAN ANTONIO', 'provincia_id' => 7],
            ['ndepartamento' => 'VALCHETA', 'provincia_id' => 7],
            ['ndepartamento' => '25 DE MAYO', 'provincia_id' => 7],
            ['ndepartamento' => 'BURRUYAC?', 'provincia_id' => 8],
            ['ndepartamento' => 'CAPITAL', 'provincia_id' => 8],
            ['ndepartamento' => 'CRUZ ALTA', 'provincia_id' => 8],
            ['ndepartamento' => 'CHICLIGASTA', 'provincia_id' => 8],
            ['ndepartamento' => 'FAMALL?', 'provincia_id' => 8],
            ['ndepartamento' => 'GRANEROS', 'provincia_id' => 8],
            ['ndepartamento' => 'JUAN B. ALBERDI', 'provincia_id' => 8],
            ['ndepartamento' => 'LA COCHA', 'provincia_id' => 8],
            ['ndepartamento' => 'LEALES', 'provincia_id' => 8],
            ['ndepartamento' => 'LULES', 'provincia_id' => 8],
            ['ndepartamento' => 'MONTEROS', 'provincia_id' => 8],
            ['ndepartamento' => 'R?O CHICO', 'provincia_id' => 8],
            ['ndepartamento' => 'SIMOCA', 'provincia_id' => 8],
            ['ndepartamento' => 'TAF? DEL VALLE', 'provincia_id' => 8],
            ['ndepartamento' => 'TAF? VIEJO', 'provincia_id' => 8],
            ['ndepartamento' => 'TRANCAS', 'provincia_id' => 8],
            ['ndepartamento' => 'YERBA BUENA', 'provincia_id' => 8],
            ['ndepartamento' => 'BELLA VISTA',  'provincia_id' =>10],
            ['ndepartamento' => 'BERËN DE ASTRADA',  'provincia_id' =>10],
            ['ndepartamento' => 'CAPITAL',  'provincia_id' =>10],
            ['ndepartamento' => 'CONCEPCIËN',  'provincia_id' =>10],
            ['ndepartamento' => 'CURUZ? CUATI?',  'provincia_id' =>10],
            ['ndepartamento' => 'EMPEDRADO',  'provincia_id' =>10],
            ['ndepartamento' => 'ESQUINA',  'provincia_id' =>10],
            ['ndepartamento' => 'GENERAL ALVEAR',  'provincia_id' =>10],
            ['ndepartamento' => 'GENERAL PAZ', 'provincia_id' => 10],
            ['ndepartamento' => 'GOYA', 'provincia_id' => 10],
            ['ndepartamento' => 'ITAT?', 'provincia_id' => 10],
            ['ndepartamento' => 'ITUZAINGË', 'provincia_id' => 10],
            ['ndepartamento' => 'LAVALLE', 'provincia_id' => 10],
            ['ndepartamento' => 'MBURUCUY?', 'provincia_id' => 10],
            ['ndepartamento' => 'MERCEDES', 'provincia_id' => 10],
            ['ndepartamento' => 'MONTE CASEROS', 'provincia_id' => 10],
            ['ndepartamento' => 'PASO DE LOS LIBRES', 'provincia_id' => 10],
            ['ndepartamento' => 'SALADAS', 'provincia_id' => 10],
            ['ndepartamento' => 'SAN COSME', 'provincia_id' => 10],
            ['ndepartamento' => 'SAN LUIS DEL PALMAR', 'provincia_id' => 10],
            ['ndepartamento' => 'SAN MART?N', 'provincia_id' => 10],
            ['ndepartamento' => 'SAN MIGUEL', 'provincia_id' => 10],
            ['ndepartamento' => 'SAN ROQUE', 'provincia_id' => 10],
            ['ndepartamento' => 'SANTO TOM?', 'provincia_id' => 10],
            ['ndepartamento' => 'SAUCE', 'provincia_id' => 10],
            ['ndepartamento' => 'AGUIRRE', 'provincia_id' => 11],
            ['ndepartamento' => 'ALBERDI', 'provincia_id' => 11],
            ['ndepartamento' => 'ATAMISQUI', 'provincia_id' => 11],
            ['ndepartamento' => 'AVELLANEDA', 'provincia_id' => 11],
            ['ndepartamento' => 'BANDA', 'provincia_id' => 11],
            ['ndepartamento' => 'BELGRANO', 'provincia_id' => 11],
            ['ndepartamento' => 'CAPITAL', 'provincia_id' => 11],
            ['ndepartamento' => 'COPO', 'provincia_id' => 11],
            ['ndepartamento' => 'CHOYA', 'provincia_id' => 11],
            ['ndepartamento' => 'FIGUEROA', 'provincia_id' => 11],
            ['ndepartamento' => 'GENERAL TABOADA', 'provincia_id' => 11],
            ['ndepartamento' => 'GUASAY?N', 'provincia_id' => 11],
            ['ndepartamento' => 'JIM?NEZ', 'provincia_id' => 11],
            ['ndepartamento' => 'JUAN F. IBARRA', 'provincia_id' => 11],
            ['ndepartamento' => 'LORETO', 'provincia_id' => 11],
            ['ndepartamento' => 'MITRE', 'provincia_id' => 11],
            ['ndepartamento' => 'MORENO', 'provincia_id' => 11],
            ['ndepartamento' => 'OJO DE AGUA', 'provincia_id' => 11],
            ['ndepartamento' => 'PELEGRINI', 'provincia_id' => 11],
            ['ndepartamento' => 'QUEBRACHOS', 'provincia_id' => 11],
            ['ndepartamento' => 'R?O HONDO', 'provincia_id' => 11],
            ['ndepartamento' => 'RIVADAVIA', 'provincia_id' => 11],
            ['ndepartamento' => 'ROBLES', 'provincia_id' => 11],
            ['ndepartamento' => 'SALAVINA', 'provincia_id' => 11],
            ['ndepartamento' => 'SAN MART?N', 'provincia_id' => 11],
            ['ndepartamento' => 'SARMIENTO', 'provincia_id' => 11],
            ['ndepartamento' => 'SIL?PICA', 'provincia_id' => 11],
            ['ndepartamento' => 'COCHINOCA', 'provincia_id' => 13],
            ['ndepartamento' => 'EL CARMEN', 'provincia_id' => 13],
            ['ndepartamento' => 'DR. MANUEL BELGRANO', 'provincia_id' => 13],
            ['ndepartamento' => 'HUMAHUACA', 'provincia_id' => 13],
            ['ndepartamento' => 'LEDESMA', 'provincia_id' => 13],
            ['ndepartamento' => 'PALPALA', 'provincia_id' => 13],
            ['ndepartamento' => 'RINCONADA', 'provincia_id' => 13],
            ['ndepartamento' => 'SAN ANTONIO', 'provincia_id' => 13],
            ['ndepartamento' => 'SAN PEDRO', 'provincia_id' => 13],
            ['ndepartamento' => 'SANTA BARBARA', 'provincia_id' => 13],
            ['ndepartamento' => 'SANTA CATALINA', 'provincia_id' => 13],
            ['ndepartamento' => 'SUSQUES', 'provincia_id' => 13],
            ['ndepartamento' => 'TILCARA', 'provincia_id' => 13],
            ['ndepartamento' => 'TUMBAYA', 'provincia_id' => 13],
            ['ndepartamento' => 'VALLE GRANDE', 'provincia_id' => 13],
            ['ndepartamento' => 'YAVI', 'provincia_id' => 13],
            ['ndepartamento' => 'BIEDMA', 'provincia_id' => 14],
            ['ndepartamento' => 'CUSHAMEN', 'provincia_id' => 14],
            ['ndepartamento' => 'ESCALANTE', 'provincia_id' => 14],
            ['ndepartamento' => 'FLORENTINO AMEGHINO', 'provincia_id' => 14],
            ['ndepartamento' => 'FUTALEUF?', 'provincia_id' => 14],
            ['ndepartamento' => 'GAIMAN', 'provincia_id' => 14],
            ['ndepartamento' => 'GASTRE', 'provincia_id' => 14],
            ['ndepartamento' => 'LANGUIÐEO', 'provincia_id' => 14],
            ['ndepartamento' => 'MARTIRES', 'provincia_id' => 14],
            ['ndepartamento' => 'PASO DE LOS INDIOS', 'provincia_id' => 14],
            ['ndepartamento' => 'RAWSON', 'provincia_id' => 14],
            ['ndepartamento' => 'R?O SENGUER', 'provincia_id' => 14],
            ['ndepartamento' => 'SARMIENTO', 'provincia_id' => 14],
            ['ndepartamento' => 'TEHUELCHES', 'provincia_id' => 14],
            ['ndepartamento' => 'TELSEN', 'provincia_id' => 14],
            ['ndepartamento' => 'R?O GRANDE', 'provincia_id' => 26],
            ['ndepartamento' => 'USHUAIA', 'provincia_id' => 26],
            ['ndepartamento' => 'APËSTOLES', 'provincia_id' => 27],
            ['ndepartamento' => 'CAINGU?S', 'provincia_id' => 27],
            ['ndepartamento' => 'CANDELARIA', 'provincia_id' => 27],
            ['ndepartamento' => 'CAPITAL', 'provincia_id' => 27],
            ['ndepartamento' => 'CONCEPCIËN', 'provincia_id' => 27],
            ['ndepartamento' => 'EL DORADO', 'provincia_id' => 27],
            ['ndepartamento' => 'GENERAL MANUEL BELGRANO', 'provincia_id' => 27],
            ['ndepartamento' => 'GUARAN?', 'provincia_id' => 27],
            ['ndepartamento' => 'IGUAZ?', 'provincia_id' => 27],
            ['ndepartamento' => 'LEANDRO N. ALEM', 'provincia_id' => 27],
            ['ndepartamento' => 'LIBERTADOR GENERAL SAN MART?N', 'provincia_id' => 27],
            ['ndepartamento' => 'MONTECARLO', 'provincia_id' => 27],
            ['ndepartamento' => 'OBER?', 'provincia_id' => 27],
            ['ndepartamento' => 'SAN IGNACIO', 'provincia_id' => 27],
            ['ndepartamento' => 'SAN JAVIER', 'provincia_id' => 27],
            ['ndepartamento' => 'SAN PEDRO', 'provincia_id' => 27],
            ['ndepartamento' => '25 DE MAYO', 'provincia_id' => 27],
            ['ndepartamento' => 'CORPEN AIKE', 'provincia_id' => 29],
            ['ndepartamento' => 'DESEADO', 'provincia_id' => 29],
            ['ndepartamento' => 'G?ER AIKE', 'provincia_id' => 29],
            ['ndepartamento' => 'LAGO ARGENTINO', 'provincia_id' => 29],
            ['ndepartamento' => 'LAGO BUENOS AIRES', 'provincia_id' => 29],
            ['ndepartamento' => 'MAGALLANES', 'provincia_id' => 29],
            ['ndepartamento' => 'R?O CHICO', 'provincia_id' => 29],
            ['ndepartamento' => 'ALMIRANTE BROWN', 'provincia_id' => 34],
            ['ndepartamento' => 'BERMEJO', 'provincia_id' => 34],
            ['ndepartamento' => 'COMANDANTE FERN?NDEZ', 'provincia_id' => 34],
            ['ndepartamento' => 'CHACABUCO', 'provincia_id' => 34],
            ['ndepartamento' => '12 DE OCTUBRE', 'provincia_id' => 34],
            ['ndepartamento' => 'FRAY JUSTO SANTA MAR?A DE ORO', 'provincia_id' => 34],
            ['ndepartamento' => 'GENERAL BELGRANO', 'provincia_id' => 34],
            ['ndepartamento' => 'GENERAL DONOVAN', 'provincia_id' => 34],
            ['ndepartamento' => 'GENERAL G?EMES', 'provincia_id' => 34],
            ['ndepartamento' => 'INDEPENDENCIA', 'provincia_id' => 34],
            ['ndepartamento' => 'LIBERTAD', 'provincia_id' => 34],
            ['ndepartamento' => 'LIBERTADOR GENERAL SAN MART?N', 'provincia_id' => 34],
            ['ndepartamento' => 'MAIP?', 'provincia_id' => 34],
            ['ndepartamento' => 'MAYOR LUIS J. FONTANA', 'provincia_id' => 34],
            ['ndepartamento' => '9 DE JULIO', 'provincia_id' => 34],
            ['ndepartamento' => 'O\'HIGGINS', 'provincia_id' => 34],
            ['ndepartamento' => 'PRESIDENCIA DE LA PLAZA', 'provincia_id' => 34],
            ['ndepartamento' => '1º DE MAYO', 'provincia_id' => 34],
            ['ndepartamento' => 'QUITILIPI', 'provincia_id' => 34],
            ['ndepartamento' => 'SAN FERNANDO', 'provincia_id' => 34],
            ['ndepartamento' => 'SAN LORENZO', 'provincia_id' => 34],
            ['ndepartamento' => 'SARGENTO CABRAL', 'provincia_id' => 34],
            ['ndepartamento' => 'TAPENAGA', 'provincia_id' => 34],
            ['ndepartamento' => '25 DE MAYO', 'provincia_id' => 34],
            ['ndepartamento' => 'ANTA', 'provincia_id' => 45],
            ['ndepartamento' => 'CACHI', 'provincia_id' => 45],
            ['ndepartamento' => 'CAFAYATE', 'provincia_id' => 45],
            ['ndepartamento' => 'CAPITAL', 'provincia_id' => 45],
            ['ndepartamento' => 'CERRILLOS', 'provincia_id' => 45],
            ['ndepartamento' => 'CHICOANA', 'provincia_id' => 45],
            ['ndepartamento' => 'GENERAL G?EMES', 'provincia_id' => 45],
            ['ndepartamento' => 'GENERAL JOS? DE SAN MART?N', 'provincia_id' => 45],
            ['ndepartamento' => 'GUACHIPAS', 'provincia_id' => 45],
            ['ndepartamento' => 'IRUY?', 'provincia_id' => 45],
            ['ndepartamento' => 'LA CALDERA', 'provincia_id' => 45],
            ['ndepartamento' => 'LA CANDELARIA', 'provincia_id' => 45],
            ['ndepartamento' => 'LA POMA', 'provincia_id' => 45],
            ['ndepartamento' => 'LA VIÐA', 'provincia_id' => 45],
            ['ndepartamento' => 'LOS ANDES', 'provincia_id' => 45],
            ['ndepartamento' => 'MET?N', 'provincia_id' => 45],
            ['ndepartamento' => 'MOLINOS', 'provincia_id' => 45],
            ['ndepartamento' => 'OR?N', 'provincia_id' => 45],
            ['ndepartamento' => 'RIVADAVIA', 'provincia_id' => 45],
            ['ndepartamento' => 'ROSARIO DE LA FRONTERA', 'provincia_id' => 45],
            ['ndepartamento' => 'ROSARIO DE LERMA', 'provincia_id' => 45],
            ['ndepartamento' => 'SAN CARLOS', 'provincia_id' => 45],
            ['ndepartamento' => 'SANTA VICTORIA', 'provincia_id' => 45],
            ['ndepartamento' => 'COLËN', 'provincia_id' => 46],
            ['ndepartamento' => 'CONCORDIA', 'provincia_id' => 46],
            ['ndepartamento' => 'DIAMANTE', 'provincia_id' => 46],
            ['ndepartamento' => 'FEDERACIËN', 'provincia_id' => 46],
            ['ndepartamento' => 'FEDERAL', 'provincia_id' => 46],
            ['ndepartamento' => 'FELICIANO', 'provincia_id' => 46],
            ['ndepartamento' => 'GUALEGUAY', 'provincia_id' => 46],
            ['ndepartamento' => 'GUALEGUAYCH?', 'provincia_id' => 46],
            ['ndepartamento' => 'ISLAS DEL IBICUY', 'provincia_id' => 46],
            ['ndepartamento' => 'LA PAZ', 'provincia_id' => 46],
            ['ndepartamento' => 'NOGOY?', 'provincia_id' => 46],
            ['ndepartamento' => 'PARAN?', 'provincia_id' => 46],
            ['ndepartamento' => 'TALA', 'provincia_id' => 46],
            ['ndepartamento' => 'URUGUAY', 'provincia_id' => 46],
            ['ndepartamento' => 'VICTORIA', 'provincia_id' => 46],
            ['ndepartamento' => 'VILLAGUAY', 'provincia_id' => 46],
            ['ndepartamento' => 'CAPITAL', 'provincia_id' => 47],
            ['ndepartamento' => 'RIVADAVIA', 'provincia_id' => 47],
            ['ndepartamento' => 'SANTA LUC?A', 'provincia_id' => 47],
            ['ndepartamento' => 'RAWSON', 'provincia_id' => 47],
            ['ndepartamento' => 'POCITO', 'provincia_id' => 47],
            ['ndepartamento' => 'ZONDA', 'provincia_id' => 47],
            ['ndepartamento' => 'ULLUM', 'provincia_id' => 47],
            ['ndepartamento' => 'CHIMBAS', 'provincia_id' => 47],
            ['ndepartamento' => '9 DE JULIO', 'provincia_id' => 47],
            ['ndepartamento' => 'ALBARDËN', 'provincia_id' => 47],
            ['ndepartamento' => 'ANGACO', 'provincia_id' => 47],
            ['ndepartamento' => 'SAN MART?N', 'provincia_id' => 47],
            ['ndepartamento' => 'CAUCETE', 'provincia_id' => 47],
            ['ndepartamento' => '25 DE MAYO', 'provincia_id' => 47],
            ['ndepartamento' => 'SARMIENTO', 'provincia_id' => 47],
            ['ndepartamento' => 'CALINGASTA', 'provincia_id' => 47],
            ['ndepartamento' => 'IGLESIA', 'provincia_id' => 47],
            ['ndepartamento' => 'J?CHAL', 'provincia_id' => 47],
            ['ndepartamento' => 'VALLE F?RTIL', 'provincia_id' => 47],
            ['ndepartamento' => 'CAPITAL', 'provincia_id' => 48],
            ['ndepartamento' => 'GENERAL ALVEAR', 'provincia_id' => 48],
            ['ndepartamento' => 'GODOY CRUZ', 'provincia_id' => 48],
            ['ndepartamento' => 'GUAYMALL?N', 'provincia_id' => 48],
            ['ndepartamento' => 'JUN?N', 'provincia_id' => 48],
            ['ndepartamento' => 'LA PAZ', 'provincia_id' => 48],
            ['ndepartamento' => 'LAS HERAS', 'provincia_id' => 48],
            ['ndepartamento' => 'LAVALLE', 'provincia_id' => 48],
            ['ndepartamento' => 'LUJ?N DE CUYO', 'provincia_id' => 48],
            ['ndepartamento' => 'MAIP?', 'provincia_id' => 48],
            ['ndepartamento' => 'MALARG?E', 'provincia_id' => 48],
            ['ndepartamento' => 'RIVADAVIA', 'provincia_id' => 48],
            ['ndepartamento' => 'SAN CARLOS', 'provincia_id' => 48],
            ['ndepartamento' => 'SAN MART?N', 'provincia_id' => 48],
            ['ndepartamento' => 'SAN RAFAEL', 'provincia_id' => 48],
            ['ndepartamento' => 'SANTA ROSA', 'provincia_id' => 48],
            ['ndepartamento' => 'TUNUY?N', 'provincia_id' => 48],
            ['ndepartamento' => 'TUPUNGATO', 'provincia_id' => 48],
            ['ndepartamento' => 'BERMEJO', 'provincia_id' => 49],
            ['ndepartamento' => 'FORMOSA', 'provincia_id' => 49],
            ['ndepartamento' => 'LAISHI', 'provincia_id' => 49],
            ['ndepartamento' => 'MATACOS', 'provincia_id' => 49],
            ['ndepartamento' => 'PATIÐO', 'provincia_id' => 49],
            ['ndepartamento' => 'PILAG?S', 'provincia_id' => 49],
            ['ndepartamento' => 'PILCOMAYO', 'provincia_id' => 49],
            ['ndepartamento' => 'PIRAN?', 'provincia_id' => 49],
            ['ndepartamento' => 'RAMËN LISTA', 'provincia_id' => 49],
            ['ndepartamento' => 'BELGRANO', 'provincia_id' => 50],
            ['ndepartamento' => 'CASEROS', 'provincia_id' => 50],
            ['ndepartamento' => 'CASTELLANOS', 'provincia_id' => 50],
            ['ndepartamento' => 'CONSTITUCIËN', 'provincia_id' => 50],
            ['ndepartamento' => 'GARAY', 'provincia_id' => 50],
            ['ndepartamento' => 'GENERAL LËPEZ', 'provincia_id' => 50],
            ['ndepartamento' => 'GENERAL OBLIGADO', 'provincia_id' => 50],
            ['ndepartamento' => 'IRIONDO', 'provincia_id' => 50],
            ['ndepartamento' => 'LA CAPITAL', 'provincia_id' => 50],
            ['ndepartamento' => 'LAS COLONIAS', 'provincia_id' => 50],
            ['ndepartamento' => '9 DE JULIO', 'provincia_id' => 50],
            ['ndepartamento' => 'ROSARIO', 'provincia_id' => 50],
            ['ndepartamento' => 'SAN CRISTOBAL', 'provincia_id' => 50],
            ['ndepartamento' => 'SAN JAVIER', 'provincia_id' => 50],
            ['ndepartamento' => 'SAN JERËNIMO', 'provincia_id' => 50],
            ['ndepartamento' => 'SAN JUSTO', 'provincia_id' => 50],
            ['ndepartamento' => 'SAN LORENZO', 'provincia_id' => 50],
            ['ndepartamento' => 'SAN MART?N', 'provincia_id' => 50],
            ['ndepartamento' => 'VERA', 'provincia_id' => 50],
            ['ndepartamento' => 'RIO PRIMERO', 'provincia_id' => 9],
            ['ndepartamento' => 'CAPITAL FEDERAL', 'provincia_id' => 25],
            ['ndepartamento' => 'MEN', 'provincia_id' => 48],
            ['ndepartamento' => 'MENDOZA', 'provincia_id' => 48],
            ['ndepartamento' => 'BUENOS AIRES', 'provincia_id' => 3],
            ['ndepartamento' => 'PEDERNERA', 'provincia_id' => 5],
            ['ndepartamento' => 'BUENOS AIRES', 'provincia_id' => 9],
            ['ndepartamento' => 'CAPITAL', 'provincia_id' => 5],
            ['ndepartamento' => 'SIN ESPECIFICAR', 'provincia_id' => 6],
            ['ndepartamento' => 'CAPITAL', 'provincia_id' => 34],
            ['ndepartamento' => 'MAR DEL PLATA', 'provincia_id' => 3],
            ['ndepartamento' => 'CAPITAL', 'provincia_id' => 3],
            ['ndepartamento' => 'CENTRO', 'provincia_id' => 3],
            ['ndepartamento' => 'COSTA SACATE', 'provincia_id' => 6],
            ['ndepartamento' => 'SIN ESPECIFICAR', 'provincia_id' => 3]
        ]);
    }
}
