<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LocalidadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('localidades')->insert([
            ['id' => 2,'nlocalidad' => 'ARAUCO','departamento_id' => 6,'codigo_postal' => '0'],
            ['id' => 3,'nlocalidad' => 'BAÑADO DE LOS PANTANOS','departamento_id' => 6,'codigo_postal' => '0'],
            ['id' => 4,'nlocalidad' => 'ESTACION MAZAN','departamento_id' => 6,'codigo_postal' => '0'],
            ['id' => 5,'nlocalidad' => 'TERMAS DE SANTA TERESITA','departamento_id' => 6,'codigo_postal' => '0'],
            ['id' => 6,'nlocalidad' => 'UDPINANGO','departamento_id' => 6,'codigo_postal' => '0'],
            ['id' => 7,'nlocalidad' => 'VILLA MAZAN','departamento_id' => 6,'codigo_postal' => '0'],
            ['id' => 9,'nlocalidad' => 'AMINGA','departamento_id' => 7,'codigo_postal' => '0'],
            ['id' => 10,'nlocalidad' => 'ANILLACO','departamento_id' => 7,'codigo_postal' => '0'],
            ['id' => 11,'nlocalidad' => 'ANJULLON','departamento_id' => 7,'codigo_postal' => '0'],
            ['id' => 12,'nlocalidad' => 'CHUQUIS','departamento_id' => 7,'codigo_postal' => '0'],
            ['id' => 13,'nlocalidad' => 'LOS MOLINOS','departamento_id' => 7,'codigo_postal' => '0'],
            ['id' => 14,'nlocalidad' => 'PINCHAS','departamento_id' => 7,'codigo_postal' => '0'],
            ['id' => 15,'nlocalidad' => 'SAN PEDRO','departamento_id' => 7,'codigo_postal' => '0'],
            ['id' => 16,'nlocalidad' => 'SANTA VERA CRUZ','departamento_id' => 7,'codigo_postal' => '0'],
            ['id' => 17,'nlocalidad' => 'AICUÑA','departamento_id' => 8,'codigo_postal' => '0'],
            ['id' => 18,'nlocalidad' => 'BANDA FLORIDA','departamento_id' => 8,'codigo_postal' => '0'],
            ['id' => 19,'nlocalidad' => 'GUANDACOL','departamento_id' => 8,'codigo_postal' => '0'],
            ['id' => 20,'nlocalidad' => 'LOS PALACIOS','departamento_id' => 8,'codigo_postal' => '0'],
            ['id' => 21,'nlocalidad' => 'PAGANCILLO','departamento_id' => 8,'codigo_postal' => '0'],
            ['id' => 22,'nlocalidad' => 'SANTA CLARA (GUANDACOL)','departamento_id' => 8,'codigo_postal' => '0'],
            ['id' => 23,'nlocalidad' => 'VILLA UNION','departamento_id' => 8,'codigo_postal' => '5350'],
            ['id' => 24,'nlocalidad' => 'CHAMICAL','departamento_id' => 3,'codigo_postal' => '5380'],
            ['id' => 25,'nlocalidad' => 'POLCO','departamento_id' => 3,'codigo_postal' => '0'],
            ['id' => 26,'nlocalidad' => 'CHILECITO','departamento_id' => 2,'codigo_postal' => '5360'],
            ['id' => 27,'nlocalidad' => 'COLONIA ANGUINAN','departamento_id' => 2,'codigo_postal' => '0'],
            ['id' => 28,'nlocalidad' => 'COLONIA CATINZACO','departamento_id' => 2,'codigo_postal' => '0'],
            ['id' => 29,'nlocalidad' => 'COLONIA MALLIGASTA','departamento_id' => 2,'codigo_postal' => '0'],
            ['id' => 30,'nlocalidad' => 'COLONIA VICHIGASTA','departamento_id' => 2,'codigo_postal' => '0'],
            ['id' => 31,'nlocalidad' => 'GUANCHIN','departamento_id' => 2,'codigo_postal' => '0'],
            ['id' => 32,'nlocalidad' => 'MALLIGASTA','departamento_id' => 2,'codigo_postal' => '0'],
            ['id' => 33,'nlocalidad' => 'MIRANDA','departamento_id' => 2,'codigo_postal' => '0'],
            ['id' => 34,'nlocalidad' => 'NONOGASTA','departamento_id' => 2,'codigo_postal' => '0'],
            ['id' => 35,'nlocalidad' => 'SAN NICOLAS','departamento_id' => 2,'codigo_postal' => '0'],
            ['id' => 36,'nlocalidad' => 'SANTA FLORENTINA','departamento_id' => 2,'codigo_postal' => '0'],
            ['id' => 37,'nlocalidad' => 'SAÑOGASTA','departamento_id' => 2,'codigo_postal' => '0'],
            ['id' => 38,'nlocalidad' => 'TILIMUQUI','departamento_id' => 2,'codigo_postal' => '0'],
            ['id' => 39,'nlocalidad' => 'VICHIGASTA','departamento_id' => 2,'codigo_postal' => '0'],
            ['id' => 40,'nlocalidad' => 'ALTO CARRIZAL','departamento_id' => 9,'codigo_postal' => '0'],
            ['id' => 41,'nlocalidad' => 'ANGULOS','departamento_id' => 9,'codigo_postal' => '0'],
            ['id' => 42,'nlocalidad' => 'ANTINACO','departamento_id' => 9,'codigo_postal' => '0'],
            ['id' => 43,'nlocalidad' => 'BAJO CARRIZAL','departamento_id' => 9,'codigo_postal' => '0'],
            ['id' => 44,'nlocalidad' => 'CAMPANAS','departamento_id' => 9,'codigo_postal' => '0'],
            ['id' => 45,'nlocalidad' => 'CHAÑARMUYO','departamento_id' => 9,'codigo_postal' => '0'],
            ['id' => 46,'nlocalidad' => 'FAMATINA','departamento_id' => 9,'codigo_postal' => '0'],
            ['id' => 47,'nlocalidad' => 'LA CUADRA','departamento_id' => 9,'codigo_postal' => '0'],
            ['id' => 48,'nlocalidad' => 'PITUIL','departamento_id' => 9,'codigo_postal' => '0'],
            ['id' => 49,'nlocalidad' => 'PLAZA VIEJA','departamento_id' => 9,'codigo_postal' => '0'],
            ['id' => 50,'nlocalidad' => 'SANTA CRUZ','departamento_id' => 9,'codigo_postal' => '0'],
            ['id' => 51,'nlocalidad' => 'SANTO DOMINGO','departamento_id' => 9,'codigo_postal' => '0'],
            ['id' => 52,'nlocalidad' => 'PUNTA DE LOS LLANOS', 'departamento_id' =>10,'codigo_postal' => '0'],
            ['id' => 53,'nlocalidad' => 'TAMA', 'departamento_id' =>10,'codigo_postal' => '0'],
            ['id' => 54,'nlocalidad' => 'CASTRO BARROS', 'departamento_id' =>11,'codigo_postal' => '0'],
            ['id' => 55,'nlocalidad' => 'CHAÑAR','departamento_id' => 11,'codigo_postal' => '5276'],
            ['id' => 56,'nlocalidad' => 'LOMA BLANCA','departamento_id' => 11,'codigo_postal' => '0'],
            ['id' => 57,'nlocalidad' => 'OLTA','departamento_id' => 11,'codigo_postal' => '5383'],
            ['id' => 58,'nlocalidad' => 'MALANZAN','departamento_id' => 12,'codigo_postal' => '0'],
            ['id' => 59,'nlocalidad' => 'NACATE','departamento_id' => 12,'codigo_postal' => '0'],
            ['id' => 60,'nlocalidad' => 'PORTEZUELO','departamento_id' => 12,'codigo_postal' => '0'],
            ['id' => 61,'nlocalidad' => 'SAN ANTONIO','departamento_id' => 12,'codigo_postal' => '0'],
            ['id' => 62,'nlocalidad' => 'EL CONDADO','departamento_id' => 13,'codigo_postal' => '0'],
            ['id' => 63,'nlocalidad' => 'VILLA CASTELLI','departamento_id' => 13,'codigo_postal' => '0'],
            ['id' => 64,'nlocalidad' => 'AMBIL','departamento_id' => 14,'codigo_postal' => '0'],
            ['id' => 65,'nlocalidad' => 'COLONIA ORTIZ DE OCAMPO','departamento_id' => 14,'codigo_postal' => '0'],
            ['id' => 66,'nlocalidad' => 'MILAGRO','departamento_id' => 14,'codigo_postal' => '5274'],
            ['id' => 67,'nlocalidad' => 'OLPAS','departamento_id' => 14,'codigo_postal' => '0'],
            ['id' => 68,'nlocalidad' => 'SANTA RITA DE CATUNA','departamento_id' => 14,'codigo_postal' => '0'],
            ['id' => 69,'nlocalidad' => 'ULAPES','departamento_id' => 15,'codigo_postal' => '5473'],
            ['id' => 72,'nlocalidad' => 'AMANA','departamento_id' => 17,'codigo_postal' => '0'],
            ['id' => 73,'nlocalidad' => 'PATQUIA','departamento_id' => 17,'codigo_postal' => '0'],
            ['id' => 74,'nlocalidad' => 'CHEPES','departamento_id' => 18,'codigo_postal' => '5470'],
            ['id' => 75,'nlocalidad' => 'DESIDERIO TELLO', 'departamento_id' =>18,'codigo_postal' => '0'],
            ['id' => 76,'nlocalidad' => 'MASCASIN', 'departamento_id' =>18,'codigo_postal' => '0'],
            ['id' => 77,'nlocalidad' => 'ALPASINCHE', 'departamento_id' =>19,'codigo_postal' => '0'],
            ['id' => 78,'nlocalidad' => 'AMUSCHINA', 'departamento_id' =>19,'codigo_postal' => '0'],
            ['id' => 79,'nlocalidad' => 'SALICAS - SAN BLAS', 'departamento_id' =>19,'codigo_postal' => '0'],
            ['id' => 80,'nlocalidad' => 'SURIYACO', 'departamento_id' =>19,'codigo_postal' => '0'],
            ['id' => 81,'nlocalidad' => 'TUYUBIL', 'departamento_id' =>19,'codigo_postal' => '0'],
            ['id' => 82,'nlocalidad' => 'VILLA SANAGASTA', 'departamento_id' =>20,'codigo_postal' => '0'],
            ['id' => 83,'nlocalidad' => 'LA CAUCHITA','departamento_id' => 6,'codigo_postal' => '0'],
            ['id' => 84,'nlocalidad' => 'LA CIMBRITA','departamento_id' => 6,'codigo_postal' => '0'],
            ['id' => 85,'nlocalidad' => 'LOS HERRERA','departamento_id' => 6,'codigo_postal' => '0'],
            ['id' => 86,'nlocalidad' => 'LOS MENA','departamento_id' => 6,'codigo_postal' => '0'],
            ['id' => 87,'nlocalidad' => 'UDPINANGO (Secci¢n Quintas - Zona Rural)','departamento_id' => 6,'codigo_postal' => '0'],
            ['id' => 88,'nlocalidad' => 'BAZAN','departamento_id' => 1,'codigo_postal' => '0'],
            ['id' => 89,'nlocalidad' => 'CARRIZAL','departamento_id' => 1,'codigo_postal' => '0'],
            ['id' => 90,'nlocalidad' => 'CEBOLLAR','departamento_id' => 1,'codigo_postal' => '0'],
            ['id' => 91,'nlocalidad' => 'COCHANGASTA','departamento_id' => 1,'codigo_postal' => '0'],
            ['id' => 92,'nlocalidad' => 'EL BARREAL','departamento_id' => 1,'codigo_postal' => '0'],
            ['id' => 93,'nlocalidad' => 'EL MEDANO','departamento_id' => 1,'codigo_postal' => '0'],
            ['id' => 94,'nlocalidad' => 'EL QUEBRACHO','departamento_id' => 1,'codigo_postal' => '0'],
            ['id' => 95,'nlocalidad' => 'EL SUNCHAL','departamento_id' => 1,'codigo_postal' => '0'],
            ['id' => 96,'nlocalidad' => 'ESTACION KILOMETRO 875','departamento_id' => 1,'codigo_postal' => '0'],
            ['id' => 97,'nlocalidad' => 'ESTACION KILOMETRO 891','departamento_id' => 1,'codigo_postal' => '0'],
            ['id' => 98,'nlocalidad' => 'LA AGUADITA DE LOS BRIZUELA','departamento_id' => 1,'codigo_postal' => '0'],
            ['id' => 99,'nlocalidad' => 'LA CALERA','departamento_id' => 1,'codigo_postal' => '0'],
            ['id' => 100,'nlocalidad' => 'LA PERSEGUIDA','departamento_id' => 1,'codigo_postal' => '0'],
            ['id' => 101,'nlocalidad' => 'LAS CATAS','departamento_id' => 1,'codigo_postal' => '0'],
            ['id' => 102,'nlocalidad' => 'LAS CLOACAS','departamento_id' => 1,'codigo_postal' => '0'],
            ['id' => 103,'nlocalidad' => 'LAS PADERCITAS','departamento_id' => 1,'codigo_postal' => '0'],
            ['id' => 104,'nlocalidad' => 'OBRAJE DE TOSCANO','departamento_id' => 1,'codigo_postal' => '0'],
            ['id' => 105,'nlocalidad' => 'POZO DE AVILA','departamento_id' => 1,'codigo_postal' => '0'],
            ['id' => 106,'nlocalidad' => 'PUERTO ALEGRE','departamento_id' => 1,'codigo_postal' => '0'],
            ['id' => 107,'nlocalidad' => 'SALADILLO','departamento_id' => 1,'codigo_postal' => '0'],
            ['id' => 108,'nlocalidad' => 'SAN ANTONIO','departamento_id' => 1,'codigo_postal' => '0'],
            ['id' => 109,'nlocalidad' => 'SAN BERNARDO','departamento_id' => 1,'codigo_postal' => '0'],
            ['id' => 110,'nlocalidad' => 'SAN JUAN','departamento_id' => 1,'codigo_postal' => '0'],
            ['id' => 111,'nlocalidad' => 'SANTO DOMINGO','departamento_id' => 1,'codigo_postal' => '0'],
            ['id' => 112,'nlocalidad' => 'SIERRA BRAVA','departamento_id' => 1,'codigo_postal' => '0'],
            ['id' => 113,'nlocalidad' => 'TALAMUYUNA','departamento_id' => 1,'codigo_postal' => '0'],
            ['id' => 114,'nlocalidad' => 'AGUA BLANCA','departamento_id' => 7,'codigo_postal' => '0'],
            ['id' => 115,'nlocalidad' => 'LAS PEÑAS','departamento_id' => 7,'codigo_postal' => '0'],
            ['id' => 116,'nlocalidad' => 'EL ALAMITO','departamento_id' => 8,'codigo_postal' => '0'],
            ['id' => 117,'nlocalidad' => 'EL ALTO','departamento_id' => 8,'codigo_postal' => '0'],
            ['id' => 118,'nlocalidad' => 'EL CARDON','departamento_id' => 8,'codigo_postal' => '0'],
            ['id' => 119,'nlocalidad' => 'EL FUERTE','departamento_id' => 8,'codigo_postal' => '0'],
            ['id' => 120,'nlocalidad' => 'LA BREA','departamento_id' => 8,'codigo_postal' => '0'],
            ['id' => 121,'nlocalidad' => 'LA CALDERITA','departamento_id' => 8,'codigo_postal' => '0'],
            ['id' => 122,'nlocalidad' => 'LA JUNTA','departamento_id' => 8,'codigo_postal' => '0'],
            ['id' => 123,'nlocalidad' => 'LA MARAVILLA','departamento_id' => 8,'codigo_postal' => '0'],
            ['id' => 124,'nlocalidad' => 'LA QUEBRADA','departamento_id' => 8,'codigo_postal' => '0'],
            ['id' => 125,'nlocalidad' => 'LA TOTORITA','departamento_id' => 8,'codigo_postal' => '0'],
            ['id' => 126,'nlocalidad' => 'LOS NACIMIENTOS','departamento_id' => 8,'codigo_postal' => '0'],
            ['id' => 127,'nlocalidad' => 'LOS PATILLOS','departamento_id' => 8,'codigo_postal' => '0'],
            ['id' => 128,'nlocalidad' => 'LOS TAMBILLOS','departamento_id' => 8,'codigo_postal' => '0'],
            ['id' => 129,'nlocalidad' => 'MINA DELINA','departamento_id' => 8,'codigo_postal' => '0'],
            ['id' => 130,'nlocalidad' => 'PASO SAN ISIDRO','departamento_id' => 8,'codigo_postal' => '0'],
            ['id' => 131,'nlocalidad' => 'PUERTO ALEGRE','departamento_id' => 8,'codigo_postal' => '0'],
            ['id' => 132,'nlocalidad' => 'AZAMASTIN','departamento_id' => 3,'codigo_postal' => '0'],
            ['id' => 133,'nlocalidad' => 'BAJITO HONDO','departamento_id' => 3,'codigo_postal' => '0'],
            ['id' => 134,'nlocalidad' => 'LA RIOJA','departamento_id' => 1,'codigo_postal' => '5300'],
        ]);
    }
}
