<?php

namespace Database\Seeders;

use App\Models\Role;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProduccionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('roles')->insert([
            ['name' => 'admin' , 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'coordinador' , 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'afiliado', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'vendedor', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'administrativo', 'created_at' => now(), 'updated_at' => now()]
        ]);

        DB::table('obra_sociales')->insert([
            ['nombre' => 'APOS', 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'OSUNLAR', 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'OSDE', 'created_at' => now(), 'updated_at' => now()]
        ]);

        DB::table('users')->insert([
            [
                'name' => 'Santiago',
                'lastname' => 'Ortiz Ocampo',
                'dni' => '12345678',
                'edad' => '28',
                'nacimiento' => '1993-04-21',
                'username' => 'sortiz',
                'email' => 'admin@mail.com',
                'email_verified_at' => now(),
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
                'remember_token' => Str::random(10),
                'role_id' => Role::ES_ADMIN,
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'name' => 'Emiliano',
                'lastname' => 'Romero',
                'dni' => '12345679',
                'edad' => '27',
                'nacimiento' => '1994-04-04',
                'username' => 'eromero',
                'email' => 'coordinador@mail.com',
                'email_verified_at' => now(),
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
                'remember_token' => Str::random(10),
                'role_id' => Role::ES_COORDINADOR,
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'name' => 'Sergio',
                'lastname' => 'Denis',
                'dni' => '12345680',
                'edad' => '27',
                'nacimiento' => '1994-04-04',
                'username' => 'sdenis',
                'email' => 'vendedor@mail.com',
                'email_verified_at' => now(),
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
                'remember_token' => Str::random(10),
                'role_id' => Role::ES_VENDEDOR,
                'created_at' => now(),
                'updated_at' => now(),

            ],
            [
                'name' => 'Juan Carlos',
                'lastname' => 'bodoque',
                'dni' => '12345681',
                'edad' => '27',
                'nacimiento' => '1994-04-04',
                'username' => 'jbodoque',
                'email' => 'administrativo@mail.com',
                'email_verified_at' => now(),
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
                'remember_token' => Str::random(10),
                'role_id' => Role::ES_ADMINISTRATIVO,
                'created_at' => now(),
                'updated_at' => now(),

            ]
            ]);

            DB::table('coordinadores')->insert([
                [
                    'codigo_coordinador' => Str::uuid(),
                    'user_id' => 2
                ]
                ]);

            DB::table('vendedores')->insert([
                [
                    'user_id' => 3,
                    'codigo_vendedor' => Str::uuid(),
                    'coordinador_id' => 1
                ]
                ]);
            DB::table('administrativos')->insert([
                [
                    'user_id' => 4,
                    'codigo_administrativo' => Str::uuid(),
                ]
                ]);

            DB::table('productos')->insert([
                [
                    'nombre' => 'Responso',
                ],
                [
                    'nombre' => 'Cremación ',
                ],
                [
                    'nombre' => 'Entrega de urna',
                ]
                ]);

            DB::table('paquetes')->insert([
                [
                    "nombre" => 'PLAN INDIVIDUAL',
                    "precio" => 1500
                ],
                [
                    "nombre" => 'PLAN MAYOR',
                    "precio" => 2000
                ],
                [
                    "nombre" => 'PLAN FAMILIA',
                    "precio" => 2300
                ]
                ]);

            DB::table('paquete_producto')->insert([
                [
                    'paquete_id' => 1,
                    'producto_id' => 1
                ],
                [
                    'paquete_id' => 1,
                    'producto_id' => 2
                ],
                [
                    'paquete_id' => 1,
                    'producto_id' => 3
                ],
                [
                    'paquete_id' => 2,
                    'producto_id' => 1,
                ],
                [
                    'paquete_id' => 2,
                    'producto_id' => 2,
                ],
                [
                    'paquete_id' => 2,
                    'producto_id' => 3,
                ],
                [
                    'paquete_id' => 3,
                    'producto_id' => 1
                ],
                [
                    'paquete_id' => 3,
                    'producto_id' => 2
                ],
                [
                    'paquete_id' => 3,
                    'producto_id' => 3
                ],
                ]);

                DB::table('paises')->insert([
                    ['npais' => 'ARGENTINA'],
                    ['npais' => 'URUGUAY'],
                    ['npais' => 'BRASIL'],
                    ['npais' => 'CHILE'],
                    ['npais' => 'BOLIVIA'],
                    ['npais' => 'VENEZUELA'],
                    ['npais' => 'ECUADOR'],
                    ['npais' => 'PARAGUAY'],
                    ['npais' => 'MEXICO'],
                    ['npais' => 'EEUU'],
                    ['npais' => 'PERU'],
                    ['npais' => 'COLOMBIA'],
                    ['npais' => 'COREA'],
                    ['npais' => 'CHINA']
                ]);

                DB::table('provincias')->insert([
                    ['id' => 1,'nprovincia' => 'LA PAMPA', 'pais_id' => 1],
                    ['id' => 2,'nprovincia' => 'NEUQUEN', 'pais_id' => 1],
                    ['id' => 3,'nprovincia' => 'BUENOS AIRES', 'pais_id' => 1],
                    ['id' => 4,'nprovincia' => 'CATAMARCA', 'pais_id' => 1],
                    ['id' => 5,'nprovincia' => 'SAN LUIS', 'pais_id' => 1],
                    ['id' => 6,'nprovincia' => 'CORDOBA', 'pais_id' => 1],
                    ['id' => 7,'nprovincia' => 'RIO NEGRO', 'pais_id' => 1],
                    ['id' => 8,'nprovincia' => 'TUCUMAN', 'pais_id' => 1],
                    ['id' => 9,'nprovincia' => 'LA RIOJA', 'pais_id' => 1],
                    ['id' => 10,'nprovincia' => 'CORRIENTES', 'pais_id' => 1],
                    ['id' => 11,'nprovincia' => 'SANTIAGO DEL ESTERO', 'pais_id' => 1],
                    ['id' => 13,'nprovincia' => 'JUJUY', 'pais_id' => 1],
                    ['id' => 14,'nprovincia' => 'CHUBUT', 'pais_id' => 1],
                    ['id' => 25,'nprovincia' => 'CAPITAL FEDERAL', 'pais_id' => 1],
                    ['id' => 26,'nprovincia' => 'TIERRA DEL FUEGO ', 'pais_id' => 1],
                    ['id' => 27,'nprovincia' => 'MISIONES ', 'pais_id' => 1],
                    ['id' => 29,'nprovincia' => 'SANTA CRUZ ', 'pais_id' => 1],
                    ['id' => 34,'nprovincia' => 'CHACO', 'pais_id' => 1],
                    ['id' => 45,'nprovincia' => 'SALTA', 'pais_id' => 1],
                    ['id' => 46,'nprovincia' => 'ENTRE RIOS', 'pais_id' => 1],
                    ['id' => 47,'nprovincia' => 'SAN JUAN', 'pais_id' => 1],
                    ['id' => 48,'nprovincia' => 'MENDOZA', 'pais_id' => 1],
                    ['id' => 49,'nprovincia' => 'FORMOSA', 'pais_id' => 1],
                    ['id' => 50,'nprovincia' => 'SANTA FE', 'pais_id' => 1]
                ]);

                DB::table('departamentos')->insert([
                    ['ndepartamento' => 'CAPITAL', 'provincia_id' => 9], 
                    ['ndepartamento' => 'CHILECITO', 'provincia_id' => 9], 
                    ['ndepartamento' => 'CHAMICAL', 'provincia_id' => 9], 
                    ['ndepartamento' => 'ARAUCO', 'provincia_id' => 9], 
                    ['ndepartamento' => 'CASTRO BARROS', 'provincia_id' => 9], 
                    ['ndepartamento' => 'CORONEL FELIPE VARELA', 'provincia_id' => 9], 
                    ['ndepartamento' => 'FAMATINA', 'provincia_id' => 9], 
                    ['ndepartamento' => 'GENERAL ANGEL V. PEÑALOZA', 'provincia_id' => 9],
                    ['ndepartamento' => 'GENERAL BELGRANO', 'provincia_id' => 9],
                    ['ndepartamento' => 'GENERAL JUAN F. QUIROGA', 'provincia_id' => 9],
                    ['ndepartamento' => 'GENERAL LAMADRID', 'provincia_id' => 9],
                    ['ndepartamento' => 'GENERAL OCAMPO', 'provincia_id' => 9],
                    ['ndepartamento' => 'GENERAL SAN MARTIN', 'provincia_id' => 9],
                    ['ndepartamento' => 'INDEPENDENCIA', 'provincia_id' => 9],
                    ['ndepartamento' => 'ROSARIO VERA PEÑALOZA', 'provincia_id' => 9],
                    ['ndepartamento' => 'SAN BLAS DE LOS SAUCES', 'provincia_id' => 9],
                    ['ndepartamento' => 'SANAGASTA', 'provincia_id' => 9],
                    ['ndepartamento' => 'VINCHINA', 'provincia_id' => 9],
                    ['ndepartamento' => 'ALMAGRO', 'provincia_id' => 3],
                    ['ndepartamento' => 'BALVANERA', 'provincia_id' => 3],
                    ['ndepartamento' => 'BARRACAS', 'provincia_id' => 3],
                    ['ndepartamento' => 'BELGRANO', 'provincia_id' => 3],
                    ['ndepartamento' => 'BOCA', 'provincia_id' => 3],
                    ['ndepartamento' => 'BOEDO', 'provincia_id' => 3],
                    ['ndepartamento' => 'CABALLITO', 'provincia_id' => 3],
                    ['ndepartamento' => 'CHACARITA', 'provincia_id' => 3],
                    ['ndepartamento' => 'COGHLAN', 'provincia_id' => 3],
                    ['ndepartamento' => 'COLEGIALES', 'provincia_id' => 3],
                    ['ndepartamento' => 'CONSTITUCIËN', 'provincia_id' => 3],
                    ['ndepartamento' => 'FLORES', 'provincia_id' => 3],
                    ['ndepartamento' => 'FLORESTA', 'provincia_id' => 3],
                    ['ndepartamento' => 'LINIERS', 'provincia_id' => 3],
                    ['ndepartamento' => 'MATADEROS', 'provincia_id' => 3],
                    ['ndepartamento' => 'MONTE CASTRO', 'provincia_id' => 3],
                    ['ndepartamento' => 'MONTSERRAT', 'provincia_id' => 3],
                    ['ndepartamento' => 'NUEVA POMPEYA', 'provincia_id' => 3],
                    ['ndepartamento' => 'NUÑEZ', 'provincia_id' => 3],
                    ['ndepartamento' => 'PALERMO', 'provincia_id' => 3],
                    ['ndepartamento' => 'PARQUE AVELLANEDA', 'provincia_id' => 3],
                    ['ndepartamento' => 'PARQUE CHACABUCO', 'provincia_id' => 3],
                    ['ndepartamento' => 'PARQUE PATRICIOS', 'provincia_id' => 3],
                    ['ndepartamento' => 'PATERNAL', 'provincia_id' => 3],
                    ['ndepartamento' => 'RECOLETA', 'provincia_id' => 3],
                    ['ndepartamento' => 'RETIRO', 'provincia_id' => 3],
                    ['ndepartamento' => 'SAAVEDRA', 'provincia_id' => 3],
                    ['ndepartamento' => 'SAN CRISTËBAL', 'provincia_id' => 3],
                    ['ndepartamento' => 'SAN NICOLAS', 'provincia_id' => 3],
                    ['ndepartamento' => 'SAN TELMO', 'provincia_id' => 3],
                    ['ndepartamento' => 'VELEZ SARSFIELD', 'provincia_id' => 3],
                    ['ndepartamento' => 'VERSALLES', 'provincia_id' => 3],
                    ['ndepartamento' => 'VILLA CRESPO', 'provincia_id' => 3],
                    ['ndepartamento' => 'VILLA DEL PARQUE', 'provincia_id' => 3],
                    ['ndepartamento' => 'VILLA DEVOTO', 'provincia_id' => 3],
                    ['ndepartamento' => 'VILLA GENERAL MITRE', 'provincia_id' => 3],
                    ['ndepartamento' => 'VILLA LUGANO', 'provincia_id' => 3],
                    ['ndepartamento' => 'VILLA LURO', 'provincia_id' => 3],
                    ['ndepartamento' => 'VILLA ORT?ZAR', 'provincia_id' => 3],
                    ['ndepartamento' => 'VILLA PUEYRREDËN', 'provincia_id' => 3],
                    ['ndepartamento' => 'VILLA REAL', 'provincia_id' => 3],
                    ['ndepartamento' => 'VILLA RIACHUELO', 'provincia_id' => 3],
                    ['ndepartamento' => 'VILLA SANTA RITA', 'provincia_id' => 3],
                    ['ndepartamento' => 'VILLA SOLDATI', 'provincia_id' => 3],
                    ['ndepartamento' => 'VILLA URQUIZA', 'provincia_id' => 3],
                    ['ndepartamento' => 'ZONA PORTUARIA', 'provincia_id' => 3],
                    ['ndepartamento' => 'ATREUCO', 'provincia_id' => 1],
                    ['ndepartamento' => 'CALEU CALEU', 'provincia_id' => 1],
                    ['ndepartamento' => 'CAPITAL', 'provincia_id' => 1],
                    ['ndepartamento' => 'CATRILË', 'provincia_id' => 1],
                    ['ndepartamento' => 'CONHELO', 'provincia_id' => 1],
                    ['ndepartamento' => 'CURACË', 'provincia_id' => 1],
                    ['ndepartamento' => 'CHALILEO', 'provincia_id' => 1],
                    ['ndepartamento' => 'CHAPALEUF?', 'provincia_id' => 1],
                    ['ndepartamento' => 'CHICAL CË', 'provincia_id' => 1],
                    ['ndepartamento' => 'GUATRACH?', 'provincia_id' => 1],
                    ['ndepartamento' => 'HUCAL', 'provincia_id' => 1],
                    ['ndepartamento' => 'UHUEL CALEL', 'provincia_id' => 1],
                    ['ndepartamento' => 'LIMAY MAHUIDA', 'provincia_id' => 1],
                    ['ndepartamento' => 'LOVENTU?', 'provincia_id' => 1],
                    ['ndepartamento' => 'MARACË', 'provincia_id' => 1],
                    ['ndepartamento' => 'PUEL?N', 'provincia_id' => 1],
                    ['ndepartamento' => 'QUEM? QUEM?', 'provincia_id' => 1],
                    ['ndepartamento' => 'RANCUL', 'provincia_id' => 1],
                    ['ndepartamento' => 'REALICË', 'provincia_id' => 1],
                    ['ndepartamento' => 'TOAY', 'provincia_id' => 1],
                    ['ndepartamento' => 'TRENEL', 'provincia_id' => 1],
                    ['ndepartamento' => 'UTRAC?N', 'provincia_id' => 1],
                    ['ndepartamento' => 'ALUMIN?', 'provincia_id' => 2],
                    ['ndepartamento' => 'AÐELO', 'provincia_id' => 2],
                    ['ndepartamento' => 'CATAN LIL', 'provincia_id' => 2],
                    ['ndepartamento' => 'COLLËN CUR?', 'provincia_id' => 2],
                    ['ndepartamento' => 'CONFLUENCIA', 'provincia_id' => 2],
                    ['ndepartamento' => 'CHOS MALAL', 'provincia_id' => 2],
                    ['ndepartamento' => 'HUILICHES', 'provincia_id' => 2],
                    ['ndepartamento' => 'LACAR', 'provincia_id' => 2],
                    ['ndepartamento' => 'LONCOPU?', 'provincia_id' => 2],
                    ['ndepartamento' => 'LOS LAGOS', 'provincia_id' => 2],
                    ['ndepartamento' => 'MINAS', 'provincia_id' => 2],
                    ['ndepartamento' => 'ÐORQU?N', 'provincia_id' => 2],
                    ['ndepartamento' => 'PEHUENCHES', 'provincia_id' => 2],
                    ['ndepartamento' => 'PIC?N LEUF?', 'provincia_id' => 2],
                    ['ndepartamento' => 'PICUNCHES', 'provincia_id' => 2],
                    ['ndepartamento' => 'ZAPALA', 'provincia_id' => 2],
                    ['ndepartamento' => 'ADOLFO ALSINA', 'provincia_id' => 3],
                    ['ndepartamento' => 'ADOLFO GONZALES CHAVES', 'provincia_id' => 3],
                    ['ndepartamento' => 'ALBERTI', 'provincia_id' => 3],
                    ['ndepartamento' => 'ALMIRANTE BROWN', 'provincia_id' => 3],
                    ['ndepartamento' => 'AVELLANEDA', 'provincia_id' => 3],
                    ['ndepartamento' => 'AYACUCHO', 'provincia_id' => 3],
                    ['ndepartamento' => 'AZUL', 'provincia_id' => 3],
                    ['ndepartamento' => 'BAH?A BLANCA', 'provincia_id' => 3],
                    ['ndepartamento' => 'BALCARCE', 'provincia_id' => 3],
                    ['ndepartamento' => 'BARADERO', 'provincia_id' => 3],
                    ['ndepartamento' => 'BARTOLOM? MITRE', 'provincia_id' => 3],
                    ['ndepartamento' => 'BENITO JUáREZ', 'provincia_id' => 3],
                    ['ndepartamento' => 'BERAZATEGUI', 'provincia_id' => 3],
                    ['ndepartamento' => 'BERISSO', 'provincia_id' => 3],
                    ['ndepartamento' => 'BOLIVAR', 'provincia_id' => 3],
                    ['ndepartamento' => 'BRAGADO', 'provincia_id' => 3],
                    ['ndepartamento' => 'BRANDSEN', 'provincia_id' => 3],
                    ['ndepartamento' => 'CAMPANA', 'provincia_id' => 3],
                    ['ndepartamento' => 'CAÐUELAS', 'provincia_id' => 3],
                    ['ndepartamento' => 'CAPIT?N SARMIENTO', 'provincia_id' => 3],
                    ['ndepartamento' => 'CARLOS CASARES', 'provincia_id' => 3],
                    ['ndepartamento' => 'CARLOS TEJEDOR', 'provincia_id' => 3],
                    ['ndepartamento' => 'CARMEN DE ARECO', 'provincia_id' => 3],
                    ['ndepartamento' => 'CASTELLI', 'provincia_id' => 3],
                    ['ndepartamento' => 'COLËN', 'provincia_id' => 3],
                    ['ndepartamento' => 'CORONEL DE MARINA L. ROSALE', 'provincia_id' => 3],
                    ['ndepartamento' => 'CORONEL DORREGO', 'provincia_id' => 3],
                    ['ndepartamento' => 'CORONEL PRINGLES', 'provincia_id' => 3],
                    ['ndepartamento' => 'CORONEL SU?REZ', 'provincia_id' => 3],
                    ['ndepartamento' => 'CHACABUCO', 'provincia_id' => 3],
                    ['ndepartamento' => 'CHASCOM?S', 'provincia_id' => 3],
                    ['ndepartamento' => 'CHIVILCOY', 'provincia_id' => 3],
                    ['ndepartamento' => 'DAIREAUX', 'provincia_id' => 3],
                    ['ndepartamento' => 'DOLORES', 'provincia_id' => 3],
                    ['ndepartamento' => 'ENSENADA', 'provincia_id' => 3],
                    ['ndepartamento' => 'ESCOBAR', 'provincia_id' => 3],
                    ['ndepartamento' => 'ESTEBAN ECHEVERR?A', 'provincia_id' => 3],
                    ['ndepartamento' => 'EXALTACIËN DE LA CRUZ', 'provincia_id' => 3],
                    ['ndepartamento' => 'FLORENCIO VARELA', 'provincia_id' => 3],
                    ['ndepartamento' => 'FLORENTINO AMEGHINO', 'provincia_id' => 3],
                    ['ndepartamento' => 'GENERAL ALVARADO', 'provincia_id' => 3],
                    ['ndepartamento' => 'GENERAL ALVEAR', 'provincia_id' => 3],
                    ['ndepartamento' => 'GENERAL ARENALES', 'provincia_id' => 3],
                    ['ndepartamento' => 'GENERAL BELGRANO', 'provincia_id' => 3],
                    ['ndepartamento' => 'GENERAL GUIDO', 'provincia_id' => 3],
                    ['ndepartamento' => 'GENERAL JUAN MADARIAGA', 'provincia_id' => 3],
                    ['ndepartamento' => 'GENERAL LA MADRID', 'provincia_id' => 3],
                    ['ndepartamento' => 'GENERAL LAS HERAS', 'provincia_id' => 3],
                    ['ndepartamento' => 'GENERAL LAVALLE', 'provincia_id' => 3],
                    ['ndepartamento' => 'GENERAL PAZ', 'provincia_id' => 3],
                    ['ndepartamento' => 'GENERAL PINTO', 'provincia_id' => 3],
                    ['ndepartamento' => 'GENERAL PUEYRREDËN', 'provincia_id' => 3],
                    ['ndepartamento' => 'GENERAL RODRIGUEZ', 'provincia_id' => 3],
                    ['ndepartamento' => 'GENERAL SAN MART?N', 'provincia_id' => 3],
                    ['ndepartamento' => 'GENERAL SARMIENTO', 'provincia_id' => 3],
                    ['ndepartamento' => 'GENERAL VIAMONTE', 'provincia_id' => 3],
                    ['ndepartamento' => 'GENERAL VILLEGAS', 'provincia_id' => 3],
                    ['ndepartamento' => 'GUAMIN?', 'provincia_id' => 3],
                    ['ndepartamento' => 'HIPËLITO YRIGOYEN', 'provincia_id' => 3],
                    ['ndepartamento' => 'JUN?N', 'provincia_id' => 3],
                    ['ndepartamento' => 'LA COSTA', 'provincia_id' => 3],
                    ['ndepartamento' => 'LA MATANZA','provincia_id' => 3],
                    ['ndepartamento' => 'LA PLATA','provincia_id' => 3],
                    ['ndepartamento' => 'LAN?S','provincia_id' => 3],
                    ['ndepartamento' => 'LAPRIDA','provincia_id' => 3],
                    ['ndepartamento' => 'LAS FLORES','provincia_id' => 3],
                    ['ndepartamento' => 'LEANDRO N. ALEM','provincia_id' => 3],
                    ['ndepartamento' => 'LINCOLN','provincia_id' => 3],
                    ['ndepartamento' => 'LOBER?A','provincia_id' => 3],
                    ['ndepartamento' => 'LOBOS','provincia_id' => 3],
                    ['ndepartamento' => 'LOMAS DE ZAMORA','provincia_id' => 3],
                    ['ndepartamento' => 'LUJ?N','provincia_id' => 3],
                    ['ndepartamento' => 'MAGDALENA','provincia_id' => 3],
                    ['ndepartamento' => 'MAIP?','provincia_id' => 3],
                    ['ndepartamento' => 'MAR CHIQUITA','provincia_id' => 3],
                    ['ndepartamento' => 'MARCOS PAZ','provincia_id' => 3],
                    ['ndepartamento' => 'MERCEDES','provincia_id' => 3],
                    ['ndepartamento' => 'MERLO','provincia_id' => 3],
                    ['ndepartamento' => 'MONTE','provincia_id' => 3],
                    ['ndepartamento' => 'MONTE HERMOSO','provincia_id' => 3],
                    ['ndepartamento' => 'MORENO','provincia_id' => 3],
                    ['ndepartamento' => 'MORËN','provincia_id' => 3],
                    ['ndepartamento' => 'NAVARRO','provincia_id' => 3],
                    ['ndepartamento' => 'NECOCHEA','provincia_id' => 3],
                    ['ndepartamento' => '9 DE JULIO','provincia_id' => 3],
                    ['ndepartamento' => 'OLAVARR?A','provincia_id' => 3],
                    ['ndepartamento' => 'PATAGONES','provincia_id' => 3],
                    ['ndepartamento' => 'PEHUAJË','provincia_id' => 3],
                    ['ndepartamento' => 'PELLEGRINI','provincia_id' => 3],
                    ['ndepartamento' => 'PERGAMINO','provincia_id' => 3],
                    ['ndepartamento' => 'PILA','provincia_id' => 3],
                    ['ndepartamento' => 'PILAR','provincia_id' => 3],
                    ['ndepartamento' => 'PINAMAR','provincia_id' => 3],
                    ['ndepartamento' => 'PU?N','provincia_id' => 3],
                    ['ndepartamento' => 'QUILMES','provincia_id' => 3],
                    ['ndepartamento' => 'RAMALLO','provincia_id' => 3],
                    ['ndepartamento' => 'RAUCH','provincia_id' => 3],
                    ['ndepartamento' => 'RIVADAVIA','provincia_id' => 3],
                    ['ndepartamento' => 'ROJAS','provincia_id' => 3],
                    ['ndepartamento' => 'ROQUE P?REZ', 'provincia_id' => 3],
                    ['ndepartamento' => 'SAAVEDRA', 'provincia_id' => 3],
                    ['ndepartamento' => 'SALADILLO', 'provincia_id' => 3],
                    ['ndepartamento' => 'SALTO', 'provincia_id' => 3],
                    ['ndepartamento' => 'SALLIQUELË', 'provincia_id' => 3],
                    ['ndepartamento' => 'SAN ANDR?S DE GILES', 'provincia_id' => 3],
                    ['ndepartamento' => 'SAN ANTONIO DE ARECO', 'provincia_id' => 3],
                    ['ndepartamento' => 'SAN CAYETANO', 'provincia_id' => 3],
                    ['ndepartamento' => 'SAN FERNANDO', 'provincia_id' => 3],
                    ['ndepartamento' => 'SAN ISIDRO', 'provincia_id' => 3],
                    ['ndepartamento' => 'SAN NICOL?S', 'provincia_id' => 3],
                    ['ndepartamento' => 'SAN PEDRO', 'provincia_id' => 3],
                    ['ndepartamento' => 'SAN VICENTE', 'provincia_id' => 3],
                    ['ndepartamento' => 'SUIPACHA', 'provincia_id' => 3],
                    ['ndepartamento' => 'TANDIL', 'provincia_id' => 3],
                    ['ndepartamento' => 'TAPALQU?', 'provincia_id' => 3],
                    ['ndepartamento' => 'TIGRE', 'provincia_id' => 3],
                    ['ndepartamento' => 'TORDILLO', 'provincia_id' => 3],
                    ['ndepartamento' => 'TORNQUIST', 'provincia_id' => 3],
                    ['ndepartamento' => 'TRENQUE LAUQUEN', 'provincia_id' => 3],
                    ['ndepartamento' => 'TRES ARROYOS', 'provincia_id' => 3],
                    ['ndepartamento' => 'TRES DE FEBRERO', 'provincia_id' => 3],
                    ['ndepartamento' => 'TRES LOMAS', 'provincia_id' => 3],
                    ['ndepartamento' => '25 DE MAYO', 'provincia_id' => 3],
                    ['ndepartamento' => 'VICENTE LËPEZ', 'provincia_id' => 3],
                    ['ndepartamento' => 'VILLA GESELL', 'provincia_id' => 3],
                    ['ndepartamento' => 'VILLARINO', 'provincia_id' => 3],
                    ['ndepartamento' => 'Z?RATE', 'provincia_id' => 3],
                    ['ndepartamento' => 'AMBATO', 'provincia_id' => 4],
                    ['ndepartamento' => 'ANCASTI', 'provincia_id' => 4],
                    ['ndepartamento' => 'ANDALGALA', 'provincia_id' => 4],
                    ['ndepartamento' => 'ANTOFAGASTA DE LA SIERRA', 'provincia_id' => 4],
                    ['ndepartamento' => 'BELEN', 'provincia_id' => 4],
                    ['ndepartamento' => 'CAPAYAN', 'provincia_id' => 4],
                    ['ndepartamento' => 'CAPITAL', 'provincia_id' => 4],
                    ['ndepartamento' => 'EL ALTO', 'provincia_id' => 4],
                    ['ndepartamento' => 'FRAY MAMERTO ESQUIU', 'provincia_id' => 4],
                    ['ndepartamento' => 'LA PAZ', 'provincia_id' => 4],
                    ['ndepartamento' => 'PACLIN', 'provincia_id' => 4],
                    ['ndepartamento' => 'POMAN', 'provincia_id' => 4],
                    ['ndepartamento' => 'SANTA MARIA', 'provincia_id' => 4],
                    ['ndepartamento' => 'SANTA ROSA', 'provincia_id' => 4],
                    ['ndepartamento' => 'TINOGASTA', 'provincia_id' => 4],
                    ['ndepartamento' => 'VALLE VIEJO', 'provincia_id' => 4],
                    ['ndepartamento' => 'AYACUCHO', 'provincia_id' => 5],
                    ['ndepartamento' => 'BELGRANO', 'provincia_id' => 5],
                    ['ndepartamento' => 'CORONEL PRINGLES', 'provincia_id' => 5],
                    ['ndepartamento' => 'CHACABUCO', 'provincia_id' => 5],
                    ['ndepartamento' => 'GENERAL PEDERNERA', 'provincia_id' => 5],
                    ['ndepartamento' => 'GOBERNADOR DUPUY', 'provincia_id' => 5],
                    ['ndepartamento' => 'JUN?N', 'provincia_id' => 5],
                    ['ndepartamento' => 'LA CAPITAL', 'provincia_id' => 5],
                    ['ndepartamento' => 'LIBERTADOR GENERAL SAN MART?N', 'provincia_id' => 5],
                    ['ndepartamento' => 'CALAMUCHITA', 'provincia_id' => 6],
                    ['ndepartamento' => 'CAPITAL', 'provincia_id' => 6],
                    ['ndepartamento' => 'COLËN', 'provincia_id' => 6],
                    ['ndepartamento' => 'CRUZ DEL EJE', 'provincia_id' => 6],
                    ['ndepartamento' => 'GENERAL ROCA', 'provincia_id' => 6],
                    ['ndepartamento' => 'GENERAL SAN MART?N', 'provincia_id' => 6],
                    ['ndepartamento' => 'ISCHIL?N', 'provincia_id' => 6],
                    ['ndepartamento' => 'JU?REZ CELMAN', 'provincia_id' => 6],
                    ['ndepartamento' => 'MARCOS JU?REZ', 'provincia_id' => 6],
                    ['ndepartamento' => 'MINAS', 'provincia_id' => 6],
                    ['ndepartamento' => 'POCHO', 'provincia_id' => 6],
                    ['ndepartamento' => 'PRESIDENTE ROQUE SáENZ PEÐA', 'provincia_id' => 6],
                    ['ndepartamento' => 'PUNILLA', 'provincia_id' => 6],
                    ['ndepartamento' => 'R?O CUARTO', 'provincia_id' => 6],
                    ['ndepartamento' => 'R?O PRIMERO', 'provincia_id' => 6],
                    ['ndepartamento' => 'R?O SECO', 'provincia_id' => 6],
                    ['ndepartamento' => 'R?O SEGUNDO', 'provincia_id' => 6],
                    ['ndepartamento' => 'SAN ALBERTO', 'provincia_id' => 6],
                    ['ndepartamento' => 'SAN JAVIER', 'provincia_id' => 6],
                    ['ndepartamento' => 'SAN JUSTO', 'provincia_id' => 6],
                    ['ndepartamento' => 'SANTA MAR?A', 'provincia_id' => 6],
                    ['ndepartamento' => 'SOBREMONTE', 'provincia_id' => 6],
                    ['ndepartamento' => 'TERCERO ARRIBA', 'provincia_id' => 6],
                    ['ndepartamento' => 'TOTORAL', 'provincia_id' => 6],
                    ['ndepartamento' => 'TULUMBA', 'provincia_id' => 6],
                    ['ndepartamento' => 'UNIËN', 'provincia_id' => 6],
                    ['ndepartamento' => 'ADOLFO ALSINA', 'provincia_id' => 7],
                    ['ndepartamento' => 'AVELLANEDA', 'provincia_id' => 7],
                    ['ndepartamento' => 'BARILOCHE', 'provincia_id' => 7],
                    ['ndepartamento' => 'CONESA', 'provincia_id' => 7],
                    ['ndepartamento' => 'EL CUY', 'provincia_id' => 7],
                    ['ndepartamento' => 'GENERAL ROCA', 'provincia_id' => 7],
                    ['ndepartamento' => '9 DE JULIO', 'provincia_id' => 7],
                    ['ndepartamento' => 'ÐORQUINCO', 'provincia_id' => 7],
                    ['ndepartamento' => 'PICHI MAHU?DA', 'provincia_id' => 7],
                    ['ndepartamento' => 'PILCANIYEU', 'provincia_id' => 7],
                    ['ndepartamento' => 'SAN ANTONIO', 'provincia_id' => 7],
                    ['ndepartamento' => 'VALCHETA', 'provincia_id' => 7],
                    ['ndepartamento' => '25 DE MAYO', 'provincia_id' => 7],
                    ['ndepartamento' => 'BURRUYAC?', 'provincia_id' => 8],
                    ['ndepartamento' => 'CAPITAL', 'provincia_id' => 8],
                    ['ndepartamento' => 'CRUZ ALTA', 'provincia_id' => 8],
                    ['ndepartamento' => 'CHICLIGASTA', 'provincia_id' => 8],
                    ['ndepartamento' => 'FAMALL?', 'provincia_id' => 8],
                    ['ndepartamento' => 'GRANEROS', 'provincia_id' => 8],
                    ['ndepartamento' => 'JUAN B. ALBERDI', 'provincia_id' => 8],
                    ['ndepartamento' => 'LA COCHA', 'provincia_id' => 8],
                    ['ndepartamento' => 'LEALES', 'provincia_id' => 8],
                    ['ndepartamento' => 'LULES', 'provincia_id' => 8],
                    ['ndepartamento' => 'MONTEROS', 'provincia_id' => 8],
                    ['ndepartamento' => 'R?O CHICO', 'provincia_id' => 8],
                    ['ndepartamento' => 'SIMOCA', 'provincia_id' => 8],
                    ['ndepartamento' => 'TAF? DEL VALLE', 'provincia_id' => 8],
                    ['ndepartamento' => 'TAF? VIEJO', 'provincia_id' => 8],
                    ['ndepartamento' => 'TRANCAS', 'provincia_id' => 8],
                    ['ndepartamento' => 'YERBA BUENA', 'provincia_id' => 8],
                    ['ndepartamento' => 'BELLA VISTA',  'provincia_id' =>10],
                    ['ndepartamento' => 'BERËN DE ASTRADA',  'provincia_id' =>10],
                    ['ndepartamento' => 'CAPITAL',  'provincia_id' =>10],
                    ['ndepartamento' => 'CONCEPCIËN',  'provincia_id' =>10],
                    ['ndepartamento' => 'CURUZ? CUATI?',  'provincia_id' =>10],
                    ['ndepartamento' => 'EMPEDRADO',  'provincia_id' =>10],
                    ['ndepartamento' => 'ESQUINA',  'provincia_id' =>10],
                    ['ndepartamento' => 'GENERAL ALVEAR',  'provincia_id' =>10],
                    ['ndepartamento' => 'GENERAL PAZ', 'provincia_id' => 10],
                    ['ndepartamento' => 'GOYA', 'provincia_id' => 10],
                    ['ndepartamento' => 'ITAT?', 'provincia_id' => 10],
                    ['ndepartamento' => 'ITUZAINGË', 'provincia_id' => 10],
                    ['ndepartamento' => 'LAVALLE', 'provincia_id' => 10],
                    ['ndepartamento' => 'MBURUCUY?', 'provincia_id' => 10],
                    ['ndepartamento' => 'MERCEDES', 'provincia_id' => 10],
                    ['ndepartamento' => 'MONTE CASEROS', 'provincia_id' => 10],
                    ['ndepartamento' => 'PASO DE LOS LIBRES', 'provincia_id' => 10],
                    ['ndepartamento' => 'SALADAS', 'provincia_id' => 10],
                    ['ndepartamento' => 'SAN COSME', 'provincia_id' => 10],
                    ['ndepartamento' => 'SAN LUIS DEL PALMAR', 'provincia_id' => 10],
                    ['ndepartamento' => 'SAN MART?N', 'provincia_id' => 10],
                    ['ndepartamento' => 'SAN MIGUEL', 'provincia_id' => 10],
                    ['ndepartamento' => 'SAN ROQUE', 'provincia_id' => 10],
                    ['ndepartamento' => 'SANTO TOM?', 'provincia_id' => 10],
                    ['ndepartamento' => 'SAUCE', 'provincia_id' => 10],
                    ['ndepartamento' => 'AGUIRRE', 'provincia_id' => 11],
                    ['ndepartamento' => 'ALBERDI', 'provincia_id' => 11],
                    ['ndepartamento' => 'ATAMISQUI', 'provincia_id' => 11],
                    ['ndepartamento' => 'AVELLANEDA', 'provincia_id' => 11],
                    ['ndepartamento' => 'BANDA', 'provincia_id' => 11],
                    ['ndepartamento' => 'BELGRANO', 'provincia_id' => 11],
                    ['ndepartamento' => 'CAPITAL', 'provincia_id' => 11],
                    ['ndepartamento' => 'COPO', 'provincia_id' => 11],
                    ['ndepartamento' => 'CHOYA', 'provincia_id' => 11],
                    ['ndepartamento' => 'FIGUEROA', 'provincia_id' => 11],
                    ['ndepartamento' => 'GENERAL TABOADA', 'provincia_id' => 11],
                    ['ndepartamento' => 'GUASAY?N', 'provincia_id' => 11],
                    ['ndepartamento' => 'JIM?NEZ', 'provincia_id' => 11],
                    ['ndepartamento' => 'JUAN F. IBARRA', 'provincia_id' => 11],
                    ['ndepartamento' => 'LORETO', 'provincia_id' => 11],
                    ['ndepartamento' => 'MITRE', 'provincia_id' => 11],
                    ['ndepartamento' => 'MORENO', 'provincia_id' => 11],
                    ['ndepartamento' => 'OJO DE AGUA', 'provincia_id' => 11],
                    ['ndepartamento' => 'PELEGRINI', 'provincia_id' => 11],
                    ['ndepartamento' => 'QUEBRACHOS', 'provincia_id' => 11],
                    ['ndepartamento' => 'R?O HONDO', 'provincia_id' => 11],
                    ['ndepartamento' => 'RIVADAVIA', 'provincia_id' => 11],
                    ['ndepartamento' => 'ROBLES', 'provincia_id' => 11],
                    ['ndepartamento' => 'SALAVINA', 'provincia_id' => 11],
                    ['ndepartamento' => 'SAN MART?N', 'provincia_id' => 11],
                    ['ndepartamento' => 'SARMIENTO', 'provincia_id' => 11],
                    ['ndepartamento' => 'SIL?PICA', 'provincia_id' => 11],
                    ['ndepartamento' => 'COCHINOCA', 'provincia_id' => 13],
                    ['ndepartamento' => 'EL CARMEN', 'provincia_id' => 13],
                    ['ndepartamento' => 'DR. MANUEL BELGRANO', 'provincia_id' => 13],
                    ['ndepartamento' => 'HUMAHUACA', 'provincia_id' => 13],
                    ['ndepartamento' => 'LEDESMA', 'provincia_id' => 13],
                    ['ndepartamento' => 'PALPALA', 'provincia_id' => 13],
                    ['ndepartamento' => 'RINCONADA', 'provincia_id' => 13],
                    ['ndepartamento' => 'SAN ANTONIO', 'provincia_id' => 13],
                    ['ndepartamento' => 'SAN PEDRO', 'provincia_id' => 13],
                    ['ndepartamento' => 'SANTA BARBARA', 'provincia_id' => 13],
                    ['ndepartamento' => 'SANTA CATALINA', 'provincia_id' => 13],
                    ['ndepartamento' => 'SUSQUES', 'provincia_id' => 13],
                    ['ndepartamento' => 'TILCARA', 'provincia_id' => 13],
                    ['ndepartamento' => 'TUMBAYA', 'provincia_id' => 13],
                    ['ndepartamento' => 'VALLE GRANDE', 'provincia_id' => 13],
                    ['ndepartamento' => 'YAVI', 'provincia_id' => 13],
                    ['ndepartamento' => 'BIEDMA', 'provincia_id' => 14],
                    ['ndepartamento' => 'CUSHAMEN', 'provincia_id' => 14],
                    ['ndepartamento' => 'ESCALANTE', 'provincia_id' => 14],
                    ['ndepartamento' => 'FLORENTINO AMEGHINO', 'provincia_id' => 14],
                    ['ndepartamento' => 'FUTALEUF?', 'provincia_id' => 14],
                    ['ndepartamento' => 'GAIMAN', 'provincia_id' => 14],
                    ['ndepartamento' => 'GASTRE', 'provincia_id' => 14],
                    ['ndepartamento' => 'LANGUIÐEO', 'provincia_id' => 14],
                    ['ndepartamento' => 'MARTIRES', 'provincia_id' => 14],
                    ['ndepartamento' => 'PASO DE LOS INDIOS', 'provincia_id' => 14],
                    ['ndepartamento' => 'RAWSON', 'provincia_id' => 14],
                    ['ndepartamento' => 'R?O SENGUER', 'provincia_id' => 14],
                    ['ndepartamento' => 'SARMIENTO', 'provincia_id' => 14],
                    ['ndepartamento' => 'TEHUELCHES', 'provincia_id' => 14],
                    ['ndepartamento' => 'TELSEN', 'provincia_id' => 14],
                    ['ndepartamento' => 'R?O GRANDE', 'provincia_id' => 26],
                    ['ndepartamento' => 'USHUAIA', 'provincia_id' => 26],
                    ['ndepartamento' => 'APËSTOLES', 'provincia_id' => 27],
                    ['ndepartamento' => 'CAINGU?S', 'provincia_id' => 27],
                    ['ndepartamento' => 'CANDELARIA', 'provincia_id' => 27],
                    ['ndepartamento' => 'CAPITAL', 'provincia_id' => 27],
                    ['ndepartamento' => 'CONCEPCIËN', 'provincia_id' => 27],
                    ['ndepartamento' => 'EL DORADO', 'provincia_id' => 27],
                    ['ndepartamento' => 'GENERAL MANUEL BELGRANO', 'provincia_id' => 27],
                    ['ndepartamento' => 'GUARAN?', 'provincia_id' => 27],
                    ['ndepartamento' => 'IGUAZ?', 'provincia_id' => 27],
                    ['ndepartamento' => 'LEANDRO N. ALEM', 'provincia_id' => 27],
                    ['ndepartamento' => 'LIBERTADOR GENERAL SAN MART?N', 'provincia_id' => 27],
                    ['ndepartamento' => 'MONTECARLO', 'provincia_id' => 27],
                    ['ndepartamento' => 'OBER?', 'provincia_id' => 27],
                    ['ndepartamento' => 'SAN IGNACIO', 'provincia_id' => 27],
                    ['ndepartamento' => 'SAN JAVIER', 'provincia_id' => 27],
                    ['ndepartamento' => 'SAN PEDRO', 'provincia_id' => 27],
                    ['ndepartamento' => '25 DE MAYO', 'provincia_id' => 27],
                    ['ndepartamento' => 'CORPEN AIKE', 'provincia_id' => 29],
                    ['ndepartamento' => 'DESEADO', 'provincia_id' => 29],
                    ['ndepartamento' => 'G?ER AIKE', 'provincia_id' => 29],
                    ['ndepartamento' => 'LAGO ARGENTINO', 'provincia_id' => 29],
                    ['ndepartamento' => 'LAGO BUENOS AIRES', 'provincia_id' => 29],
                    ['ndepartamento' => 'MAGALLANES', 'provincia_id' => 29],
                    ['ndepartamento' => 'R?O CHICO', 'provincia_id' => 29],
                    ['ndepartamento' => 'ALMIRANTE BROWN', 'provincia_id' => 34],
                    ['ndepartamento' => 'BERMEJO', 'provincia_id' => 34],
                    ['ndepartamento' => 'COMANDANTE FERN?NDEZ', 'provincia_id' => 34],
                    ['ndepartamento' => 'CHACABUCO', 'provincia_id' => 34],
                    ['ndepartamento' => '12 DE OCTUBRE', 'provincia_id' => 34],
                    ['ndepartamento' => 'FRAY JUSTO SANTA MAR?A DE ORO', 'provincia_id' => 34],
                    ['ndepartamento' => 'GENERAL BELGRANO', 'provincia_id' => 34],
                    ['ndepartamento' => 'GENERAL DONOVAN', 'provincia_id' => 34],
                    ['ndepartamento' => 'GENERAL G?EMES', 'provincia_id' => 34],
                    ['ndepartamento' => 'INDEPENDENCIA', 'provincia_id' => 34],
                    ['ndepartamento' => 'LIBERTAD', 'provincia_id' => 34],
                    ['ndepartamento' => 'LIBERTADOR GENERAL SAN MART?N', 'provincia_id' => 34],
                    ['ndepartamento' => 'MAIP?', 'provincia_id' => 34],
                    ['ndepartamento' => 'MAYOR LUIS J. FONTANA', 'provincia_id' => 34],
                    ['ndepartamento' => '9 DE JULIO', 'provincia_id' => 34],
                    ['ndepartamento' => 'O\'HIGGINS', 'provincia_id' => 34],
                    ['ndepartamento' => 'PRESIDENCIA DE LA PLAZA', 'provincia_id' => 34],
                    ['ndepartamento' => '1º DE MAYO', 'provincia_id' => 34],
                    ['ndepartamento' => 'QUITILIPI', 'provincia_id' => 34],
                    ['ndepartamento' => 'SAN FERNANDO', 'provincia_id' => 34],
                    ['ndepartamento' => 'SAN LORENZO', 'provincia_id' => 34],
                    ['ndepartamento' => 'SARGENTO CABRAL', 'provincia_id' => 34],
                    ['ndepartamento' => 'TAPENAGA', 'provincia_id' => 34],
                    ['ndepartamento' => '25 DE MAYO', 'provincia_id' => 34],
                    ['ndepartamento' => 'ANTA', 'provincia_id' => 45],
                    ['ndepartamento' => 'CACHI', 'provincia_id' => 45],
                    ['ndepartamento' => 'CAFAYATE', 'provincia_id' => 45],
                    ['ndepartamento' => 'CAPITAL', 'provincia_id' => 45],
                    ['ndepartamento' => 'CERRILLOS', 'provincia_id' => 45],
                    ['ndepartamento' => 'CHICOANA', 'provincia_id' => 45],
                    ['ndepartamento' => 'GENERAL G?EMES', 'provincia_id' => 45],
                    ['ndepartamento' => 'GENERAL JOS? DE SAN MART?N', 'provincia_id' => 45],
                    ['ndepartamento' => 'GUACHIPAS', 'provincia_id' => 45],
                    ['ndepartamento' => 'IRUY?', 'provincia_id' => 45],
                    ['ndepartamento' => 'LA CALDERA', 'provincia_id' => 45],
                    ['ndepartamento' => 'LA CANDELARIA', 'provincia_id' => 45],
                    ['ndepartamento' => 'LA POMA', 'provincia_id' => 45],
                    ['ndepartamento' => 'LA VIÐA', 'provincia_id' => 45],
                    ['ndepartamento' => 'LOS ANDES', 'provincia_id' => 45],
                    ['ndepartamento' => 'MET?N', 'provincia_id' => 45],
                    ['ndepartamento' => 'MOLINOS', 'provincia_id' => 45],
                    ['ndepartamento' => 'OR?N', 'provincia_id' => 45],
                    ['ndepartamento' => 'RIVADAVIA', 'provincia_id' => 45],
                    ['ndepartamento' => 'ROSARIO DE LA FRONTERA', 'provincia_id' => 45],
                    ['ndepartamento' => 'ROSARIO DE LERMA', 'provincia_id' => 45],
                    ['ndepartamento' => 'SAN CARLOS', 'provincia_id' => 45],
                    ['ndepartamento' => 'SANTA VICTORIA', 'provincia_id' => 45],
                    ['ndepartamento' => 'COLËN', 'provincia_id' => 46],
                    ['ndepartamento' => 'CONCORDIA', 'provincia_id' => 46],
                    ['ndepartamento' => 'DIAMANTE', 'provincia_id' => 46],
                    ['ndepartamento' => 'FEDERACIËN', 'provincia_id' => 46],
                    ['ndepartamento' => 'FEDERAL', 'provincia_id' => 46],
                    ['ndepartamento' => 'FELICIANO', 'provincia_id' => 46],
                    ['ndepartamento' => 'GUALEGUAY', 'provincia_id' => 46],
                    ['ndepartamento' => 'GUALEGUAYCH?', 'provincia_id' => 46],
                    ['ndepartamento' => 'ISLAS DEL IBICUY', 'provincia_id' => 46],
                    ['ndepartamento' => 'LA PAZ', 'provincia_id' => 46],
                    ['ndepartamento' => 'NOGOY?', 'provincia_id' => 46],
                    ['ndepartamento' => 'PARAN?', 'provincia_id' => 46],
                    ['ndepartamento' => 'TALA', 'provincia_id' => 46],
                    ['ndepartamento' => 'URUGUAY', 'provincia_id' => 46],
                    ['ndepartamento' => 'VICTORIA', 'provincia_id' => 46],
                    ['ndepartamento' => 'VILLAGUAY', 'provincia_id' => 46],
                    ['ndepartamento' => 'CAPITAL', 'provincia_id' => 47],
                    ['ndepartamento' => 'RIVADAVIA', 'provincia_id' => 47],
                    ['ndepartamento' => 'SANTA LUC?A', 'provincia_id' => 47],
                    ['ndepartamento' => 'RAWSON', 'provincia_id' => 47],
                    ['ndepartamento' => 'POCITO', 'provincia_id' => 47],
                    ['ndepartamento' => 'ZONDA', 'provincia_id' => 47],
                    ['ndepartamento' => 'ULLUM', 'provincia_id' => 47],
                    ['ndepartamento' => 'CHIMBAS', 'provincia_id' => 47],
                    ['ndepartamento' => '9 DE JULIO', 'provincia_id' => 47],
                    ['ndepartamento' => 'ALBARDËN', 'provincia_id' => 47],
                    ['ndepartamento' => 'ANGACO', 'provincia_id' => 47],
                    ['ndepartamento' => 'SAN MART?N', 'provincia_id' => 47],
                    ['ndepartamento' => 'CAUCETE', 'provincia_id' => 47],
                    ['ndepartamento' => '25 DE MAYO', 'provincia_id' => 47],
                    ['ndepartamento' => 'SARMIENTO', 'provincia_id' => 47],
                    ['ndepartamento' => 'CALINGASTA', 'provincia_id' => 47],
                    ['ndepartamento' => 'IGLESIA', 'provincia_id' => 47],
                    ['ndepartamento' => 'J?CHAL', 'provincia_id' => 47],
                    ['ndepartamento' => 'VALLE F?RTIL', 'provincia_id' => 47],
                    ['ndepartamento' => 'CAPITAL', 'provincia_id' => 48],
                    ['ndepartamento' => 'GENERAL ALVEAR', 'provincia_id' => 48],
                    ['ndepartamento' => 'GODOY CRUZ', 'provincia_id' => 48],
                    ['ndepartamento' => 'GUAYMALL?N', 'provincia_id' => 48],
                    ['ndepartamento' => 'JUN?N', 'provincia_id' => 48],
                    ['ndepartamento' => 'LA PAZ', 'provincia_id' => 48],
                    ['ndepartamento' => 'LAS HERAS', 'provincia_id' => 48],
                    ['ndepartamento' => 'LAVALLE', 'provincia_id' => 48],
                    ['ndepartamento' => 'LUJ?N DE CUYO', 'provincia_id' => 48],
                    ['ndepartamento' => 'MAIP?', 'provincia_id' => 48],
                    ['ndepartamento' => 'MALARG?E', 'provincia_id' => 48],
                    ['ndepartamento' => 'RIVADAVIA', 'provincia_id' => 48],
                    ['ndepartamento' => 'SAN CARLOS', 'provincia_id' => 48],
                    ['ndepartamento' => 'SAN MART?N', 'provincia_id' => 48],
                    ['ndepartamento' => 'SAN RAFAEL', 'provincia_id' => 48],
                    ['ndepartamento' => 'SANTA ROSA', 'provincia_id' => 48],
                    ['ndepartamento' => 'TUNUY?N', 'provincia_id' => 48],
                    ['ndepartamento' => 'TUPUNGATO', 'provincia_id' => 48],
                    ['ndepartamento' => 'BERMEJO', 'provincia_id' => 49],
                    ['ndepartamento' => 'FORMOSA', 'provincia_id' => 49],
                    ['ndepartamento' => 'LAISHI', 'provincia_id' => 49],
                    ['ndepartamento' => 'MATACOS', 'provincia_id' => 49],
                    ['ndepartamento' => 'PATIÐO', 'provincia_id' => 49],
                    ['ndepartamento' => 'PILAG?S', 'provincia_id' => 49],
                    ['ndepartamento' => 'PILCOMAYO', 'provincia_id' => 49],
                    ['ndepartamento' => 'PIRAN?', 'provincia_id' => 49],
                    ['ndepartamento' => 'RAMËN LISTA', 'provincia_id' => 49],
                    ['ndepartamento' => 'BELGRANO', 'provincia_id' => 50],
                    ['ndepartamento' => 'CASEROS', 'provincia_id' => 50],
                    ['ndepartamento' => 'CASTELLANOS', 'provincia_id' => 50],
                    ['ndepartamento' => 'CONSTITUCIËN', 'provincia_id' => 50],
                    ['ndepartamento' => 'GARAY', 'provincia_id' => 50],
                    ['ndepartamento' => 'GENERAL LËPEZ', 'provincia_id' => 50],
                    ['ndepartamento' => 'GENERAL OBLIGADO', 'provincia_id' => 50],
                    ['ndepartamento' => 'IRIONDO', 'provincia_id' => 50],
                    ['ndepartamento' => 'LA CAPITAL', 'provincia_id' => 50],
                    ['ndepartamento' => 'LAS COLONIAS', 'provincia_id' => 50],
                    ['ndepartamento' => '9 DE JULIO', 'provincia_id' => 50],
                    ['ndepartamento' => 'ROSARIO', 'provincia_id' => 50],
                    ['ndepartamento' => 'SAN CRISTOBAL', 'provincia_id' => 50],
                    ['ndepartamento' => 'SAN JAVIER', 'provincia_id' => 50],
                    ['ndepartamento' => 'SAN JERËNIMO', 'provincia_id' => 50],
                    ['ndepartamento' => 'SAN JUSTO', 'provincia_id' => 50],
                    ['ndepartamento' => 'SAN LORENZO', 'provincia_id' => 50],
                    ['ndepartamento' => 'SAN MART?N', 'provincia_id' => 50],
                    ['ndepartamento' => 'VERA', 'provincia_id' => 50],
                    ['ndepartamento' => 'RIO PRIMERO', 'provincia_id' => 9],
                    ['ndepartamento' => 'CAPITAL FEDERAL', 'provincia_id' => 25],
                    ['ndepartamento' => 'MEN', 'provincia_id' => 48],
                    ['ndepartamento' => 'MENDOZA', 'provincia_id' => 48],
                    ['ndepartamento' => 'BUENOS AIRES', 'provincia_id' => 3],
                    ['ndepartamento' => 'PEDERNERA', 'provincia_id' => 5],
                    ['ndepartamento' => 'BUENOS AIRES', 'provincia_id' => 9],
                    ['ndepartamento' => 'CAPITAL', 'provincia_id' => 5],
                    ['ndepartamento' => 'SIN ESPECIFICAR', 'provincia_id' => 6],
                    ['ndepartamento' => 'CAPITAL', 'provincia_id' => 34],
                    ['ndepartamento' => 'MAR DEL PLATA', 'provincia_id' => 3],
                    ['ndepartamento' => 'CAPITAL', 'provincia_id' => 3],
                    ['ndepartamento' => 'CENTRO', 'provincia_id' => 3],
                    ['ndepartamento' => 'COSTA SACATE', 'provincia_id' => 6],
                    ['ndepartamento' => 'SIN ESPECIFICAR', 'provincia_id' => 3]
                ]);

                DB::table('localidades')->insert([
                    ['id' => 2,'nlocalidad' => 'ARAUCO','departamento_id' => 6,'codigo_postal' => '0'],
                    ['id' => 3,'nlocalidad' => 'BAÑADO DE LOS PANTANOS','departamento_id' => 6,'codigo_postal' => '0'],
                    ['id' => 4,'nlocalidad' => 'ESTACION MAZAN','departamento_id' => 6,'codigo_postal' => '0'],
                    ['id' => 5,'nlocalidad' => 'TERMAS DE SANTA TERESITA','departamento_id' => 6,'codigo_postal' => '0'],
                    ['id' => 6,'nlocalidad' => 'UDPINANGO','departamento_id' => 6,'codigo_postal' => '0'],
                    ['id' => 7,'nlocalidad' => 'VILLA MAZAN','departamento_id' => 6,'codigo_postal' => '0'],
                    ['id' => 9,'nlocalidad' => 'AMINGA','departamento_id' => 7,'codigo_postal' => '0'],
                    ['id' => 10,'nlocalidad' => 'ANILLACO','departamento_id' => 7,'codigo_postal' => '0'],
                    ['id' => 11,'nlocalidad' => 'ANJULLON','departamento_id' => 7,'codigo_postal' => '0'],
                    ['id' => 12,'nlocalidad' => 'CHUQUIS','departamento_id' => 7,'codigo_postal' => '0'],
                    ['id' => 13,'nlocalidad' => 'LOS MOLINOS','departamento_id' => 7,'codigo_postal' => '0'],
                    ['id' => 14,'nlocalidad' => 'PINCHAS','departamento_id' => 7,'codigo_postal' => '0'],
                    ['id' => 15,'nlocalidad' => 'SAN PEDRO','departamento_id' => 7,'codigo_postal' => '0'],
                    ['id' => 16,'nlocalidad' => 'SANTA VERA CRUZ','departamento_id' => 7,'codigo_postal' => '0'],
                    ['id' => 17,'nlocalidad' => 'AICUÑA','departamento_id' => 8,'codigo_postal' => '0'],
                    ['id' => 18,'nlocalidad' => 'BANDA FLORIDA','departamento_id' => 8,'codigo_postal' => '0'],
                    ['id' => 19,'nlocalidad' => 'GUANDACOL','departamento_id' => 8,'codigo_postal' => '0'],
                    ['id' => 20,'nlocalidad' => 'LOS PALACIOS','departamento_id' => 8,'codigo_postal' => '0'],
                    ['id' => 21,'nlocalidad' => 'PAGANCILLO','departamento_id' => 8,'codigo_postal' => '0'],
                    ['id' => 22,'nlocalidad' => 'SANTA CLARA (GUANDACOL)','departamento_id' => 8,'codigo_postal' => '0'],
                    ['id' => 23,'nlocalidad' => 'VILLA UNION','departamento_id' => 8,'codigo_postal' => '5350'],
                    ['id' => 24,'nlocalidad' => 'CHAMICAL','departamento_id' => 3,'codigo_postal' => '5380'],
                    ['id' => 25,'nlocalidad' => 'POLCO','departamento_id' => 3,'codigo_postal' => '0'],
                    ['id' => 26,'nlocalidad' => 'CHILECITO','departamento_id' => 2,'codigo_postal' => '5360'],
                    ['id' => 27,'nlocalidad' => 'COLONIA ANGUINAN','departamento_id' => 2,'codigo_postal' => '0'],
                    ['id' => 28,'nlocalidad' => 'COLONIA CATINZACO','departamento_id' => 2,'codigo_postal' => '0'],
                    ['id' => 29,'nlocalidad' => 'COLONIA MALLIGASTA','departamento_id' => 2,'codigo_postal' => '0'],
                    ['id' => 30,'nlocalidad' => 'COLONIA VICHIGASTA','departamento_id' => 2,'codigo_postal' => '0'],
                    ['id' => 31,'nlocalidad' => 'GUANCHIN','departamento_id' => 2,'codigo_postal' => '0'],
                    ['id' => 32,'nlocalidad' => 'MALLIGASTA','departamento_id' => 2,'codigo_postal' => '0'],
                    ['id' => 33,'nlocalidad' => 'MIRANDA','departamento_id' => 2,'codigo_postal' => '0'],
                    ['id' => 34,'nlocalidad' => 'NONOGASTA','departamento_id' => 2,'codigo_postal' => '0'],
                    ['id' => 35,'nlocalidad' => 'SAN NICOLAS','departamento_id' => 2,'codigo_postal' => '0'],
                    ['id' => 36,'nlocalidad' => 'SANTA FLORENTINA','departamento_id' => 2,'codigo_postal' => '0'],
                    ['id' => 37,'nlocalidad' => 'SAÑOGASTA','departamento_id' => 2,'codigo_postal' => '0'],
                    ['id' => 38,'nlocalidad' => 'TILIMUQUI','departamento_id' => 2,'codigo_postal' => '0'],
                    ['id' => 39,'nlocalidad' => 'VICHIGASTA','departamento_id' => 2,'codigo_postal' => '0'],
                    ['id' => 40,'nlocalidad' => 'ALTO CARRIZAL','departamento_id' => 9,'codigo_postal' => '0'],
                    ['id' => 41,'nlocalidad' => 'ANGULOS','departamento_id' => 9,'codigo_postal' => '0'],
                    ['id' => 42,'nlocalidad' => 'ANTINACO','departamento_id' => 9,'codigo_postal' => '0'],
                    ['id' => 43,'nlocalidad' => 'BAJO CARRIZAL','departamento_id' => 9,'codigo_postal' => '0'],
                    ['id' => 44,'nlocalidad' => 'CAMPANAS','departamento_id' => 9,'codigo_postal' => '0'],
                    ['id' => 45,'nlocalidad' => 'CHAÑARMUYO','departamento_id' => 9,'codigo_postal' => '0'],
                    ['id' => 46,'nlocalidad' => 'FAMATINA','departamento_id' => 9,'codigo_postal' => '0'],
                    ['id' => 47,'nlocalidad' => 'LA CUADRA','departamento_id' => 9,'codigo_postal' => '0'],
                    ['id' => 48,'nlocalidad' => 'PITUIL','departamento_id' => 9,'codigo_postal' => '0'],
                    ['id' => 49,'nlocalidad' => 'PLAZA VIEJA','departamento_id' => 9,'codigo_postal' => '0'],
                    ['id' => 50,'nlocalidad' => 'SANTA CRUZ','departamento_id' => 9,'codigo_postal' => '0'],
                    ['id' => 51,'nlocalidad' => 'SANTO DOMINGO','departamento_id' => 9,'codigo_postal' => '0'],
                    ['id' => 52,'nlocalidad' => 'PUNTA DE LOS LLANOS', 'departamento_id' =>10,'codigo_postal' => '0'],
                    ['id' => 53,'nlocalidad' => 'TAMA', 'departamento_id' =>10,'codigo_postal' => '0'],
                    ['id' => 54,'nlocalidad' => 'CASTRO BARROS', 'departamento_id' =>11,'codigo_postal' => '0'],
                    ['id' => 55,'nlocalidad' => 'CHAÑAR','departamento_id' => 11,'codigo_postal' => '5276'],
                    ['id' => 56,'nlocalidad' => 'LOMA BLANCA','departamento_id' => 11,'codigo_postal' => '0'],
                    ['id' => 57,'nlocalidad' => 'OLTA','departamento_id' => 11,'codigo_postal' => '5383'],
                    ['id' => 58,'nlocalidad' => 'MALANZAN','departamento_id' => 12,'codigo_postal' => '0'],
                    ['id' => 59,'nlocalidad' => 'NACATE','departamento_id' => 12,'codigo_postal' => '0'],
                    ['id' => 60,'nlocalidad' => 'PORTEZUELO','departamento_id' => 12,'codigo_postal' => '0'],
                    ['id' => 61,'nlocalidad' => 'SAN ANTONIO','departamento_id' => 12,'codigo_postal' => '0'],
                    ['id' => 62,'nlocalidad' => 'EL CONDADO','departamento_id' => 13,'codigo_postal' => '0'],
                    ['id' => 63,'nlocalidad' => 'VILLA CASTELLI','departamento_id' => 13,'codigo_postal' => '0'],
                    ['id' => 64,'nlocalidad' => 'AMBIL','departamento_id' => 14,'codigo_postal' => '0'],
                    ['id' => 65,'nlocalidad' => 'COLONIA ORTIZ DE OCAMPO','departamento_id' => 14,'codigo_postal' => '0'],
                    ['id' => 66,'nlocalidad' => 'MILAGRO','departamento_id' => 14,'codigo_postal' => '5274'],
                    ['id' => 67,'nlocalidad' => 'OLPAS','departamento_id' => 14,'codigo_postal' => '0'],
                    ['id' => 68,'nlocalidad' => 'SANTA RITA DE CATUNA','departamento_id' => 14,'codigo_postal' => '0'],
                    ['id' => 69,'nlocalidad' => 'ULAPES','departamento_id' => 15,'codigo_postal' => '5473'],
                    ['id' => 72,'nlocalidad' => 'AMANA','departamento_id' => 17,'codigo_postal' => '0'],
                    ['id' => 73,'nlocalidad' => 'PATQUIA','departamento_id' => 17,'codigo_postal' => '0'],
                    ['id' => 74,'nlocalidad' => 'CHEPES','departamento_id' => 18,'codigo_postal' => '5470'],
                    ['id' => 75,'nlocalidad' => 'DESIDERIO TELLO', 'departamento_id' =>18,'codigo_postal' => '0'],
                    ['id' => 76,'nlocalidad' => 'MASCASIN', 'departamento_id' =>18,'codigo_postal' => '0'],
                    ['id' => 77,'nlocalidad' => 'ALPASINCHE', 'departamento_id' =>19,'codigo_postal' => '0'],
                    ['id' => 78,'nlocalidad' => 'AMUSCHINA', 'departamento_id' =>19,'codigo_postal' => '0'],
                    ['id' => 79,'nlocalidad' => 'SALICAS - SAN BLAS', 'departamento_id' =>19,'codigo_postal' => '0'],
                    ['id' => 80,'nlocalidad' => 'SURIYACO', 'departamento_id' =>19,'codigo_postal' => '0'],
                    ['id' => 81,'nlocalidad' => 'TUYUBIL', 'departamento_id' =>19,'codigo_postal' => '0'],
                    ['id' => 82,'nlocalidad' => 'VILLA SANAGASTA', 'departamento_id' =>20,'codigo_postal' => '0'],
                    ['id' => 83,'nlocalidad' => 'LA CAUCHITA','departamento_id' => 6,'codigo_postal' => '0'],
                    ['id' => 84,'nlocalidad' => 'LA CIMBRITA','departamento_id' => 6,'codigo_postal' => '0'],
                    ['id' => 85,'nlocalidad' => 'LOS HERRERA','departamento_id' => 6,'codigo_postal' => '0'],
                    ['id' => 86,'nlocalidad' => 'LOS MENA','departamento_id' => 6,'codigo_postal' => '0'],
                    ['id' => 87,'nlocalidad' => 'UDPINANGO (Secci¢n Quintas - Zona Rural)','departamento_id' => 6,'codigo_postal' => '0'],
                    ['id' => 88,'nlocalidad' => 'BAZAN','departamento_id' => 1,'codigo_postal' => '0'],
                    ['id' => 89,'nlocalidad' => 'CARRIZAL','departamento_id' => 1,'codigo_postal' => '0'],
                    ['id' => 90,'nlocalidad' => 'CEBOLLAR','departamento_id' => 1,'codigo_postal' => '0'],
                    ['id' => 91,'nlocalidad' => 'COCHANGASTA','departamento_id' => 1,'codigo_postal' => '0'],
                    ['id' => 92,'nlocalidad' => 'EL BARREAL','departamento_id' => 1,'codigo_postal' => '0'],
                    ['id' => 93,'nlocalidad' => 'EL MEDANO','departamento_id' => 1,'codigo_postal' => '0'],
                    ['id' => 94,'nlocalidad' => 'EL QUEBRACHO','departamento_id' => 1,'codigo_postal' => '0'],
                    ['id' => 95,'nlocalidad' => 'EL SUNCHAL','departamento_id' => 1,'codigo_postal' => '0'],
                    ['id' => 96,'nlocalidad' => 'ESTACION KILOMETRO 875','departamento_id' => 1,'codigo_postal' => '0'],
                    ['id' => 97,'nlocalidad' => 'ESTACION KILOMETRO 891','departamento_id' => 1,'codigo_postal' => '0'],
                    ['id' => 98,'nlocalidad' => 'LA AGUADITA DE LOS BRIZUELA','departamento_id' => 1,'codigo_postal' => '0'],
                    ['id' => 99,'nlocalidad' => 'LA CALERA','departamento_id' => 1,'codigo_postal' => '0'],
                    ['id' => 100,'nlocalidad' => 'LA PERSEGUIDA','departamento_id' => 1,'codigo_postal' => '0'],
                    ['id' => 101,'nlocalidad' => 'LAS CATAS','departamento_id' => 1,'codigo_postal' => '0'],
                    ['id' => 102,'nlocalidad' => 'LAS CLOACAS','departamento_id' => 1,'codigo_postal' => '0'],
                    ['id' => 103,'nlocalidad' => 'LAS PADERCITAS','departamento_id' => 1,'codigo_postal' => '0'],
                    ['id' => 104,'nlocalidad' => 'OBRAJE DE TOSCANO','departamento_id' => 1,'codigo_postal' => '0'],
                    ['id' => 105,'nlocalidad' => 'POZO DE AVILA','departamento_id' => 1,'codigo_postal' => '0'],
                    ['id' => 106,'nlocalidad' => 'PUERTO ALEGRE','departamento_id' => 1,'codigo_postal' => '0'],
                    ['id' => 107,'nlocalidad' => 'SALADILLO','departamento_id' => 1,'codigo_postal' => '0'],
                    ['id' => 108,'nlocalidad' => 'SAN ANTONIO','departamento_id' => 1,'codigo_postal' => '0'],
                    ['id' => 109,'nlocalidad' => 'SAN BERNARDO','departamento_id' => 1,'codigo_postal' => '0'],
                    ['id' => 110,'nlocalidad' => 'SAN JUAN','departamento_id' => 1,'codigo_postal' => '0'],
                    ['id' => 111,'nlocalidad' => 'SANTO DOMINGO','departamento_id' => 1,'codigo_postal' => '0'],
                    ['id' => 112,'nlocalidad' => 'SIERRA BRAVA','departamento_id' => 1,'codigo_postal' => '0'],
                    ['id' => 113,'nlocalidad' => 'TALAMUYUNA','departamento_id' => 1,'codigo_postal' => '0'],
                    ['id' => 114,'nlocalidad' => 'AGUA BLANCA','departamento_id' => 7,'codigo_postal' => '0'],
                    ['id' => 115,'nlocalidad' => 'LAS PEÑAS','departamento_id' => 7,'codigo_postal' => '0'],
                    ['id' => 116,'nlocalidad' => 'EL ALAMITO','departamento_id' => 8,'codigo_postal' => '0'],
                    ['id' => 117,'nlocalidad' => 'EL ALTO','departamento_id' => 8,'codigo_postal' => '0'],
                    ['id' => 118,'nlocalidad' => 'EL CARDON','departamento_id' => 8,'codigo_postal' => '0'],
                    ['id' => 119,'nlocalidad' => 'EL FUERTE','departamento_id' => 8,'codigo_postal' => '0'],
                    ['id' => 120,'nlocalidad' => 'LA BREA','departamento_id' => 8,'codigo_postal' => '0'],
                    ['id' => 121,'nlocalidad' => 'LA CALDERITA','departamento_id' => 8,'codigo_postal' => '0'],
                    ['id' => 122,'nlocalidad' => 'LA JUNTA','departamento_id' => 8,'codigo_postal' => '0'],
                    ['id' => 123,'nlocalidad' => 'LA MARAVILLA','departamento_id' => 8,'codigo_postal' => '0'],
                    ['id' => 124,'nlocalidad' => 'LA QUEBRADA','departamento_id' => 8,'codigo_postal' => '0'],
                    ['id' => 125,'nlocalidad' => 'LA TOTORITA','departamento_id' => 8,'codigo_postal' => '0'],
                    ['id' => 126,'nlocalidad' => 'LOS NACIMIENTOS','departamento_id' => 8,'codigo_postal' => '0'],
                    ['id' => 127,'nlocalidad' => 'LOS PATILLOS','departamento_id' => 8,'codigo_postal' => '0'],
                    ['id' => 128,'nlocalidad' => 'LOS TAMBILLOS','departamento_id' => 8,'codigo_postal' => '0'],
                    ['id' => 129,'nlocalidad' => 'MINA DELINA','departamento_id' => 8,'codigo_postal' => '0'],
                    ['id' => 130,'nlocalidad' => 'PASO SAN ISIDRO','departamento_id' => 8,'codigo_postal' => '0'],
                    ['id' => 131,'nlocalidad' => 'PUERTO ALEGRE','departamento_id' => 8,'codigo_postal' => '0'],
                    ['id' => 132,'nlocalidad' => 'AZAMASTIN','departamento_id' => 3,'codigo_postal' => '0'],
                    ['id' => 133,'nlocalidad' => 'BAJITO HONDO','departamento_id' => 3,'codigo_postal' => '0'],
                    ['id' => 134,'nlocalidad' => 'LA RIOJA','departamento_id' => 1,'codigo_postal' => '5300'],
                ]);

                DB::table('barrios')->insert([
                    ['id' => 15,'nbarrio' => 'CENTRO ', 'localidad_id' => 134,],
                    ['id' => 16,'nbarrio' => 'SAN MARTIN ', 'localidad_id' => 134,],
                    ['id' => 17,'nbarrio' => 'ARGENTINO ', 'localidad_id' => 134,],
                    ['id' => 18,'nbarrio' => 'MATADERO ', 'localidad_id' => 134,],
                    ['id' => 19,'nbarrio' => 'CARDONAL ', 'localidad_id' => 134,],
                    ['id' => 20,'nbarrio' => 'HOSPITAL ', 'localidad_id' => 134,],
                    ['id' => 21,'nbarrio' => 'VARGAS ', 'localidad_id' => 134,],
                    ['id' => 22,'nbarrio' => 'BENJAMIN RINCON ', 'localidad_id' => 134,],
                    ['id' => 23,'nbarrio' => 'FACUNDO QUIROGA ', 'localidad_id' => 134,],
                    ['id' => 24,'nbarrio' => 'ANTARTIDA I ', 'localidad_id' => 134,],
                    ['id' => 25,'nbarrio' => 'NUEVA ARGENTINA ', 'localidad_id' => 134,],
                    ['id' => 27,'nbarrio' => 'SAN CAYETANO ', 'localidad_id' => 134,],
                    ['id' => 28,'nbarrio' => 'ANTARTIDA II ', 'localidad_id' => 134,],
                    ['id' => 29,'nbarrio' => 'FERROVIARIO ', 'localidad_id' => 134,],
                    ['id' => 30,'nbarrio' => 'SHINCAL ', 'localidad_id' => 134,],
                    ['id' => 31,'nbarrio' => 'LA HERMITA ', 'localidad_id' => 134,],
                    ['id' => 32,'nbarrio' => 'PARQUE SUR ', 'localidad_id' => 134,],
                    ['id' => 33,'nbarrio' => 'COCHANGASTA', 'localidad_id' => 134,],
                    ['id' => 34,'nbarrio' => 'EVITA ', 'localidad_id' => 134,],
                    ['id' => 35,'nbarrio' => 'ISLAS MALVINAS ', 'localidad_id' => 134,],
                    ['id' => 36,'nbarrio' => 'SAN VICENTE ', 'localidad_id' => 134,],
                    ['id' => 37,'nbarrio' => 'INFANTERIA II ', 'localidad_id' => 134,],
                    ['id' => 38,'nbarrio' => 'LAS BREAS ', 'localidad_id' => 134,],
                    ['id' => 39,'nbarrio' => 'CEMENTERIO ', 'localidad_id' => 134,],
                    ['id' => 40,'nbarrio' => 'LOS OLIVARES ', 'localidad_id' => 134,],
                    ['id' => 41,'nbarrio' => 'LA HERMITILLA ', 'localidad_id' => 134,],
                    ['id' => 42,'nbarrio' => 'SIN ESPECIFICAR','localicad_id' => 26,],
                    ['id' => 43,'nbarrio' => 'FEDERACION I ', 'localidad_id' => 134,],
                    ['id' => 44,'nbarrio' => 'FALDEO DEL VELAZCO SUR ', 'localidad_id' => 134,],
                    ['id' => 45,'nbarrio' => '88 VIVIENDAS ', 'localidad_id' => 134,],
                    ['id' => 46,'nbarrio' => 'PARQUE INDUSTRIAL ', 'localidad_id' => 134,],
                    ['id' => 47,'nbarrio' => 'SAN ROMAN ', 'localidad_id' => 134,],
                    ['id' => 48,'nbarrio' => 'MERCANTIL ', 'localidad_id' => 134,],
                    ['id' => 49,'nbarrio' => 'LOS FILTROS ', 'localidad_id' => 134,],
                    ['id' => 50,'nbarrio' => 'TAMBOR DE TACUARI ', 'localidad_id' => 134,],
                    ['id' => 51,'nbarrio' => 'LA QUEBRADA ', 'localidad_id' => 134,],
                    ['id' => 52,'nbarrio' => 'PANAMERICANO ', 'localidad_id' => 134,],
                    ['id' => 53,'nbarrio' => '9 DE JULIO 55', 'localidad_id' => 134,],
                    ['id' => 54,'nbarrio' => 'U.P.C.N ', 'localidad_id' => 134,],
                    ['id' => 55,'nbarrio' => 'JARDIN RESIDENCIAL ', 'localidad_id' => 134,],
                    ['id' => 56,'nbarrio' => 'EL CARDONAL ', 'localidad_id' => 134,],
                    ['id' => 57,'nbarrio' => 'ALTA RIOJA ', 'localidad_id' => 134,],
                    ['id' => 58,'nbarrio' => 'SIN ESPECIFICAR', 'localidad_id' => 134,],
                    ['id' => 59,'nbarrio' => 'CENTRO ','localidad_id' => 26,],
                    ['id' => 60,'nbarrio' => 'SIN ESPECIFICAR','localidad_id' => 24,],
                    ['id' => 61,'nbarrio' => 'SAN CLEMENTE ', 'localidad_id' => 134,],
                    ['id' => 62,'nbarrio' => 'JOAQUIN VICTOR GONZALEZ ', 'localidad_id' => 134,],
                    //(63, 'LA PUNILLA ', 664, 'S'),
                    ['id' => 64,'nbarrio' => 'RAMIREZ DE VELAZCO ', 'localidad_id' => 134,],
                    ['id' => 65,'nbarrio' => 'TIRO FEDERAL ', 'localidad_id' => 134,],
                ]);

                DB::table('calles')->insert([
                    ['id' => 13,'ncalle' => 'PELAGIO B. LUNA ', 'localidad_id' => 134,],
                    ['id' => 14,'ncalle' => 'SAN NICOLAS DE BARI ', 'localidad_id' => 134,],
                    ['id' => 15,'ncalle' => 'CATAMARCA ', 'localidad_id' => 134,],
                    ['id' => 16,'ncalle' => 'RIVADAVIA ', 'localidad_id' => 134,],
                    ['id' => 17,'ncalle' => 'BUENOS AIRES ', 'localidad_id' => 134,],
                    ['id' => 18,'ncalle' => 'LAMADRID ', 'localidad_id' => 134,],
                    ['id' => 19,'ncalle' => '9 DE JULIO ', 'localidad_id' => 134,],
                    ['id' => 20,'ncalle' => 'SAN MARTIN ', 'localidad_id' => 134,],
                    ['id' => 21,'ncalle' => 'AV. PERON', 'localidad_id' => 134,],
                    ['id' => 22,'ncalle' => 'COPIAPO ', 'localidad_id' => 134,],
                    ['id' => 23,'ncalle' => 'JUJUY ', 'localidad_id' => 134,],
                    ['id' => 24,'ncalle' => 'AYAN OESTE','localidad_id' =>  24,],
                    ['id' => 25,'ncalle' => 'DALMACIO VELEZ SARFIELD ', 'localidad_id' => 134,],
                    ['id' => 26,'ncalle' => 'RIO NEGRO ', 'localidad_id' => 134,],
                    ['id' => 27,'ncalle' => 'JUSTO JOSE DE URQUIZA ', 'localidad_id' => 134,],
                    ['id' => 28,'ncalle' => 'RAMIREZ DE VELAZCO', 'localidad_id' => 134,],
                    ['id' => 29,'ncalle' => 'EL CHACHO ', 'localidad_id' => 134,],
                    ['id' => 30,'ncalle' => 'CHARRUAS ', 'localidad_id' => 134,],
                    ['id' => 31,'ncalle' => 'FACUNDO QUIROGA ', 'localidad_id' => 134,],
                    ['id' => 32,'ncalle' => 'SAN ISIDRO ', 'localidad_id' => 134,],
                    ['id' => 33,'ncalle' => 'FRANCISCO SOLANO GOMEZ ', 'localidad_id' => 134,],
                    ['id' => 34,'ncalle' => 'INDEPENDENCIA ', 'localidad_id' => 134,],
                    ['id' => 35,'ncalle' => 'ISLA DECEPCION ', 'localidad_id' => 134,],
                    ['id' => 36,'ncalle' => 'JOAQUIN VICTOR GONZALEZ ', 'localidad_id' => 134,],
                ]);
    }
}
